################################################
## General Configuration
################################################
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages

################################################
## Customize
################################################
  customize:
    package.node_anchors:
      customize: &customize
        package: 'configuration'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Components
################################################
ios:
  push:
    categories:
      - name: Meds Not Taken
        identifier: 'meds_not_taken'
        actions:
          - identifier: 'mark_meds_taken'
            title: 'Mark meds as taken'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

logbook:
config:
conversation:
history:
#map:
zeroconf:
tts:

################################################
## Input Boolean
################################################
input_boolean:
  automation_mode:
    name: "Automation Mode"
    initial: off
    icon: mdi:human-male-female
  vacation_mode:
    name: "Vacation Mode"
    initial: off
    icon: mdi:human-male-female
  woonkamer_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  hal_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  tv_status_woonkamer:
    name: "TV Status - Woonkamer"
    initial: off

##########################################
##### Group
##########################################
group:
  default_view:
    icon: mdi:home
    view: yes
    entities:
      - device_tracker.taipan5g
      - device_tracker.lieke_iphone
      - sensor.power_consumption
      - group.slaapkamer_boris_camera
      - group.scripts_on
      - group.scripts_off
      - group.location_control
      - group.trash_pickup
      - group.meds_reminder
      - group.printer_sensors
      - group.sensors
      - group.media
      - group.logger
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_wind_speed

  network_view:
    icon: mdi:server-network
    view: yes
    entities:
      - group.woonkamer_speedtest

  woonkamer_speedtest:
    name: "Internet Speedtest"
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping

  printer_sensors:
    name: "Printer Sensors"
    entities:
      - sensor.samsung_printer
      - sensor.samsung_printer_toner_black
      - sensor.samsung_printer_tray_1
      - sensor.samsung_printer_output_tray_0

  sensors:
    name: "Sensors"
    entities:
  #    - sensor.plex_activity
  #    - input_boolean.woonkamer_motion
  #    - sensor.woonkamer_motion
  #    - sensor.switch_woonkamer
  #    - sensor.switch_hal_en_overlopen
      - sensor.time
      - sensor.date
  #    - sun.sun
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.week_of_year
      - sensor.day_of_year
  #    - sensor.next_sunrise
  #    - sensor.next_sunset
  #    - sensor.solar_angle
      - sensor.moon


################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      time_of_day:
        friendly_name: 'Time of Day'
        value_template: >-
          {% if   now().strftime("%H:%M") < "06:00" %} night
          {% elif now().strftime("%H:%M") < "09:00" %} early morning
          {% elif now().strftime("%H:%M") < "11:30" %} morning
          {% elif now().strftime("%H:%M") < "13:30" %} lunchtime
          {% elif now().strftime("%H:%M") < "16:00" %} afternoon
          {% elif now().strftime("%H:%M") < "19:00" %} evening
          {% elif now().strftime("%H:%M") < "21:00" %} late evening
          {% elif now().strftime("%H:%M") < "24:00" %} night
          {% endif %}
      sunset_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
        friendly_name: "Sunset"
      sunrise_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
        friendly_name: "Sunrise"
      solar_angle:
        value_template: '{{ states.sun.sun.attributes.elevation }}'
        friendly_name: "Solar Angle"
        unit_of_measurement: degrees
      next_sunrise:
        friendly_name: "Next Sunrise"
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%d.%m.%Y %-H:%M") }}'
        icon_template: mdi:weather-sunset-up
      next_sunset:
        friendly_name: "Next Sunset"
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%d.%m.%Y %-H:%M") }}'
        icon_template: mdi:weather-sunset-down
      day_of_year:
        friendly_name: "Day Number"
        value_template: '{{ now().strftime("%j") }}'
      week_of_year:
        friendly_name: "Week Number"
        value_template: '{{ now().strftime("%U") }}'

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  - platform: moon

  - platform: uptime

  - platform: speedtest
    server_id: 13218
    minute:
      - 0
    monitored_conditions:
      - ping
      - download
      - upload

