################################################
## General Configuration
################################################
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

################################################
## Customize
################################################
  customize:
    package.node_anchors:
      customize: &customize
        package: 'configuration'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Components
################################################
ios:
  push:
    categories:
      - name: Medicijnen
        identifier: 'medicijnen'
        actions:
          - identifier: 'MARK_MEDS_TAKEN'
            title: 'Medicijnen ingenomen'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: Afval
        identifier: 'afval'
        actions:
          - identifier: 'MARK_TRASH_MOVED'
            title: 'Afval verwerkt'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: Wasmachine
        identifier: 'wasmachine'
        actions:
          - identifier: 'MARK_WAS_DONE'
            title: 'Wasmachine klaar'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

logbook:
config:
conversation:
history:
#map:
zeroconf:
tts:
python_script:

################################################
## Input Boolean
################################################
input_boolean:
  automation_mode:
    name: "Automation Mode"
    initial: off
    icon: mdi:human-male-female
  vacation_mode:
    name: "Vacation Mode"
    initial: off
    icon: mdi:human-male-female
  woonkamer_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  hal_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  tv_status_woonkamer:
    name: "TV Status - Woonkamer"
    initial: off

################################################
## Sensor
################################################
sensor:
#  - platform: template
#    sensors:
#      time_of_day:
#        friendly_name: 'Time of Day'
#        value_template: >-
#          {% if   now().strftime("%H:%M") < "06:00" %} late night
#          {% elif now().strftime("%H:%M") < "08:00" %} early morning
#          {% elif now().strftime("%H:%M") < "10:30" %} morning
#          {% elif now().strftime("%H:%M") < "13:00" %} lunchtime
#          {% elif now().strftime("%H:%M") < "16:00" %} afternoon
#          {% elif now().strftime("%H:%M") < "19:00" %} evening
#          {% elif now().strftime("%H:%M") < "22:00" %} late evening
#          {% elif now().strftime("%H:%M") < "24:00" %} night
#          {% endif %}
#      sunset_time:
#        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
#        friendly_name: "Sunset"
#      sunrise_time:
#        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
#        friendly_name: "Sunrise"
#      solar_angle:
#        value_template: '{{ states.sun.sun.attributes.elevation }}'
#        friendly_name: "Solar Angle"
#        unit_of_measurement: degrees
#      next_sunrise:
#        friendly_name: "Next Sunrise"
#        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%d.%m.%Y %-H:%M") }}'
#        icon_template: mdi:weather-sunset-up
#      next_sunset:
#        friendly_name: "Next Sunset"
#        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%d.%m.%Y %-H:%M") }}'
#        icon_template: mdi:weather-sunset-down
#      day_of_year:
#        friendly_name: "Day Number"
#        value_template: '{{ now().strftime("%j") }}'
#      week_of_year:
#        friendly_name: "Week Number"
#        value_template: '{{ now().strftime("%U") }}'
#
#sensor.time_of_day:
#sensor.next_sunrise:
#sensor.next_sunset:
#sensor.day_of_year:
#sensor.week_of_year:

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  - platform: moon

  - platform: uptime

  - platform: speedtest
    server_id: 13218
    minute:
      - 0
    monitored_conditions:
      - ping
      - download
      - upload

