################################################
## Packages / Home-Assistant
################################################
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   #- type: trusted_networks
   #- type: legacy_api_password

http:
#  api_password: !secret http_password
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  ip_ban_enabled: false
  login_attempts_threshold: 5
  trusted_proxies:
    - 127.0.0.1
    - ::1
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - fd00::/8

auth:
logbook:
config:
conversation:
history:
map:
zeroconf:
system_health:

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168.0.15:8123

lovelace:
  mode: yaml

custom_updater:  # https://github.com/custom-components/custom_updater/wiki/Installation
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    #- python_scripts
  card_urls:
    - https://raw.githubusercontent.com/maykar/custom-lovelace/master/tracker.json
    - https://raw.githubusercontent.com/custom-cards/information/master/repos.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/xirixiz/home-assistant-config/master/custom_updater.json
    # - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
