resources:
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: /local/custom-lovelace/tracker-card/tracker-card.js?v=0.1.5
    type: js

name: Home
views:
  ################################################
  ## HOME
  ################################################
  - id: 0  # Automatically created id
    icon: mdi:home-assistant
    title: Home
    cards:
      - id: 634f213a3d2f480faf0e4172ae4c0e4e  # Automatically created id
        type: entities
        entities:
          - device_tracker.taipan5g
          - device_tracker.lieke_iphone

      - id: aedc813edd634881b238ec562b68643b  # Automatically created id
        type: entities
        entities:
          - input_boolean.vacation_mode
          - input_boolean.automation_mode

      - id: 831a7ae69913420388b01fa8b4b3a77f  # Automatically created id
        type: entities
        entities:
          - script.all_on
          - script.all_on_bright
          - script.all_on_super_bright
          - script.all_off
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - scene.slaapkamer_general
          - scene.slaapkamer_bright
          - scene.slaapkamer_night
          - scene.slaapkamer_wakeup
          - scene.slaapkamer_off
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - input_number.keuken_hanglamp_brightness
          - group.kerstmis
          - switch.smartplug2
          - switch.smartplug4
          - switch.smartplug7

      #- type: thermostat
      #  entity: climate.living_room
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.living_room_thermostat_temperature
            name: Temperatuur
          - type: sensor
            entity: sensor.living_room_thermostat_humidity
            name: Luchtvochtigheid
        - id: dcb17306a9af4348ac01a6969ccb5ebe  # Automatically created id
          type: entities
          entities:
            - input_number.woonkamer_nest_thermostat_temperature
            - climate.living_room

      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.electricity_currently_delivered
        - type: horizontal-stack
          cards:
          - type: sensor
            entity: sensor.smartplug1_watts
            name: Wasmachine
          - type: sensor
            entity: sensor.smartplug3_watts
            name: Droger
        - id: 4ec3917eb0bb4154a6bc45c1ea3f7feb  # Automatically created id
          type: entities
          entities:
            - sensor.smartplug2_watts
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            #- sensor.smartplug1_watts
            #- sensor.wasmachine_this_week
            #- sensor.percent_wasmachine_weekly
            #- sensor.wasmachine_this_month
            #- sensor.percent_wasmachine_monthly
            - sensor.wasmachine_status_time
            - sensor.wasmachine_status_value
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            #- sensor.smartplug3_watts
            #- sensor.droger_this_week
            #- sensor.percent_droger_weekly
            #- sensor.droger_this_month
            #- sensor.percent_droger_monthly
            - sensor.droger_status_time
            - sensor.droger_status_value

        - type: vertical-stack
          cards:
            - type: horizontal-stack
              cards:
                - type: picture-entity
                  entity: sensor.trash_today
                  name: Vandaag
                  state_image:
                    'gft': /local/mijnafvalwijzer/gft3.png
                    'papier': /local/mijnafvalwijzer/papier3.png
                    'restafval': /local/mijnafvalwijzer/rest3.png
                    'pmd': /local/mijnafvalwijzer/plastic3.png
                    'Geen': /local/mijnafvalwijzer/kliko3.png
                - type: picture-entity
                  entity: sensor.trash_tomorrow
                  name: Morgen
                  state_image:
                    'gft': /local/mijnafvalwijzer/gft3.png
                    'papier': /local/mijnafvalwijzer/papier3.png
                    'restafval': /local/mijnafvalwijzer/rest3.png
                    'pmd': /local/mijnafvalwijzer/plastic3.png
                    'Geen': /local/mijnafvalwijzer/kliko3.png
            - type: glance
              entities:
               - entity: sensor.trash_gft_formatted
                 name: GFT
               - entity: sensor.trash_papier_formatted
                 name: Papier
               - entity: sensor.trash_pmd_formatted
                 name: Plastic
               - entity: sensor.trash_restafval_formatted
                 name: Restafval

#      - id: 294517673fc146a4971cd37ef41fcbe1  # Automatically created id
#        type: entities
#        entities:
#          - sensor.trash_today
#          - sensor.trash_tomorrow
#          - type: divider
#            style:
#              height: 1px
#              margin-left: auto
#              margin-right: auto
#              background: '#62717b'
#          - sensor.trash_gft
#          - sensor.trash_restafval
#          - sensor.trash_papier
#          - sensor.trash_pmd
#          - type: divider
#            style:
#              height: 1px
#              margin-left: auto
#              margin-right: auto
#              background: '#62717b'
#          - input_boolean.trash_moved
#          - input_boolean.trash_reminder

      - id: 274799b9eb634da6985a9cedd0d83017  # Automatically created id
        type: entities
        entities:
          - input_boolean.meds_taken
          - input_boolean.meds_reminder


  ################################################
  ## WEATHER
  ################################################
  - id: 1  # Automatically created id
    icon: mdi:weather-cloudy
    title: Weather
    cards:
      - id: a98182cd273c467b821cc203c6b7faeb  # Automatically created id
        type: entities
        title: Thermostats
        entities:
          - input_number.woonkamer_nest_thermostat_temperature
          - sensor.hal_temperature
          - sensor.woonkamer_temperature
          - sensor.slaapkamer_boris_temperature
          - sensor.living_room_thermostat_temperature
          - sensor.living_room_thermostat_target
          - sensor.living_room_thermostat_operation_mode
          - sensor.living_room_thermostat_humidity

      - id: 5221011e50c1439281a9312c7af145b2  # Automatically created id
        type: weather-forecast
        title: Weather
        entity: weather.yweather

      - id: 911ad6f392ca4ff5b2b1b0c5d335f2ea  # Automatically created id
        type: iframe
        aspect_ratio: 88%
        url: https://embed.windy.com/embed2.html?rainAccu,50.912,5.067,7


  ################################################
  ## CAMERAS/SECURITY
  ################################################
  - id: 2  # Automatically created id
    icon: mdi:cctv
    title: Cameras
    cards:
      - type: vertical-stack
        cards:
          - id: d8ccc6c98f794edab22d64dff6c78522  # Automatically created id
            type: picture-entity
            entity: camera.front_door_voordeur
            show_name: false
            show_state: false
          - id: fb7710eeba984a5b8d026b8e2347ef83  # Automatically created id
            type: picture-entity
            entity: camera.boriscam
            show_name: false
            show_state: false
          - id: f57bc50ad329439790f9ff6550f9a298  # Automatically created id
            type: picture-entity
            entity: camera.lexcam
            show_name: false
            show_state: false

  ################################################
  ## MEDIA
  ################################################
  - id: 3  # Automatically created id
    icon: mdi:play-circle-outline
    title: Media
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - sensor.livingroom_tv_this_week
              - sensor.percent_livingroom_tv_weekly
              - sensor.livingroom_tv_this_month
              - sensor.percent_livingroom_tv_monthly
          - id: dc8acb366fa24c06914feb5d1018e7b5  # Automatically created id
            type: media-control
            entity: media_player.livingroom_tv

      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - sensor.bedroom_tv_this_week
              - sensor.percent_bedroom_tv_weekly
              - sensor.bedroom_tv_this_month
              - sensor.percent_bedroom_tv_monthly
          - id: e3df08f0e7dd44d3b2df12172ee60305  # Automatically created id
            type: media-control
            entity: media_player.bedroom_tv

      - id: 181bd7fa7ff4473db8188d295eea08a7  # Automatically created id
        type: entities
        title: Plex Activity
        entities:
          - sensor.plex_activity

  ################################################
  ## POWER
  ################################################
  - id: 4  # Automatically created id
    icon: mdi:power-plug
    title: Energy
    cards:
      - type: sensor
        entity: sensor.electricity_currently_delivered
        name: DSMR - Huidig

      - type: sensor
        entity: sensor.electricity1
        name: DSMR - Totaal Energie

      - type: sensor
        entity: sensor.gas
        name: DSMR - Totaal Gas

      - id: c941976202ab41f8a9d3772ca5008dc7  # Automatically created id
        type: custom:monster-card
        card:
          type: entities
          title: Huidige Energie Verbruikers
        filter:
          include:
            - domain: light
              state: on

      - id: 52332e8847ee451e82d59429353094df  # Automatically created id
        type: entities
        title: HUE Sensors
        entities:
          - sensor.hue_remote_1_state
          - sensor.hue_remote_1_last_update
          - sensor.hue_remote_1_battery
          - sensor.hue_remote_2_state
          - sensor.hue_remote_2_last_update
          - sensor.hue_remote_2_battery
          - sensor.woonkamer_motion
          - sensor.switch_woonkamer
          - sensor.woonkamer_lux
          - sensor.woonkamer_battery
          - sensor.hal_motion
          - sensor.switch_hal
          - sensor.hal_lux
          - sensor.hal_battery

      - id: 8fc7f03aadb4410c9fbcf1ce1baec60f  # Automatically created id
        type: entities
        title: Nest Protect
        entities:
          - sensor.living_room_nest_protect_co_status
          - sensor.living_room_nest_protect_smoke_status
          - sensor.living_room_nest_protect_battery_health
          - sensor.entryway_nest_protect_co_status
          - sensor.entryway_nest_protect_smoke_status
          - sensor.entryway_nest_protect_battery_health
          - sensor.upstairs_nest_protect_co_status
          - sensor.upstairs_nest_protect_smoke_status
          - sensor.upstairs_nest_protect_battery_health

      - id: 2f8e283fb9fc445cb3f5deaf3e33cf59  # Automatically created id
        type: entities
        title: Nest Hello
        entities:
          - binary_sensor.front_door_camera_voordeur_online
          - binary_sensor.front_door_camera_voordeur_motion_detected
          - binary_sensor.front_door_camera_voordeur_person_detected
          - binary_sensor.front_door_camera_voordeur_sound_detected

  ################################################
  ## NETWORK/INTERNET
  ################################################
  - id: 5  # Automatically created id
    icon: mdi:network
    title: Network
    cards:
      - id: 3fe5628fb1af4581ac183ca52e110db9  # Automatically created id
        type: entities
        title: Pi-Hole
        entities:
          - sensor.pihole_status
          - script.enable_pihole
          - input_select.pihole_time
          - sensor.pihole_ads_blocked_today
          - sensor.pihole_ads_percentage_blocked_today
          - sensor.pihole_dns_queries_cached
          - sensor.pihole_dns_queries_forwarded
          - sensor.pihole_dns_queries_today
          - sensor.pihole_dns_unique_clients
          - sensor.pihole_dns_unique_domains
          - sensor.pihole_domains_blocked
          - sensor.pihole_seen_clients

      - type: custom:tracker-card
        title: Custom Card Updates
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

      - type: entities
        title: HASS
        entities:
          - sensor.uptime
          - sensor.ha_installed_version
          - sensor.ha_current_version

      - type: entities
        title: Synology
        entities:
          - sensor.cpu_load_total
          - sensor.memory_usage_real
          - sensor.status_smart_sda
          - sensor.status_smart_sdb
          - sensor.status_smart_sdc
          - sensor.temperature_sda
          - sensor.temperature_sdb
          - sensor.temperature_sdc
          - sensor.volume_used_volume_1
          - sensor.total_size_volume_1

      - id: 46c741ff7cfc4491a6b3712909c80469  # Automatically created id
        type: entities
        title: Internet
        entities:
          - sensor.external_ip
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping

      - id: a9b870b423a14aabaab904e4b37d6fc4  # Automatically created id
        type: entities
        title: Printer
        entities:
          - sensor.samsung_printer
          - sensor.samsung_printer_toner_black
          - sensor.samsung_printer_tray_1
          - sensor.samsung_printer_output_tray_0

  ################################################
  ## SETTINGS/TESTING
  ################################################
  - id: 6  # Automatically created id
    icon: mdi:settings
    title: Settings
    cards:
      - id: 7b93b97d36d449729c9e45775313200b  # Automatically created id
        type: entities
        entities:
          - input_select.current_theme

      - id: 6442b597c98341909b8cf2d0a6adf750  # Automatically created id
        type: custom:monster-card
        card:
          type: entities
          title: All Automations
        filter:
          include:
            - domain: automation
              state: on
