resources:
  - url: /local/monster-card.js
    type: js
name: Home
views:
  - icon: mdi:home-assistant
    title: Home
    #theme: darkblue
    cards:
      - type: entities
        entities:
          - device_tracker.taipan5g
          - device_tracker.lieke_iphone
      - type: entities
        entities:
          - script.all_on
          - script.all_on_bright
          - script.all_on_super_bright
          - script.all_off
#          - input_select.light_scenes
      - type: entities
        entities:
          - sensor.electricity_currently_delivered
          - sensor.electricity1
          - sensor.gas
      - type: entities
        entities:
          - input_boolean.meds_taken
          - input_boolean.meds_reminder
      - type: entities
        entities:
          - input_boolean.vacation_mode
          - input_boolean.automation_mode
      - type: picture-entity
        entity: camera.front_door_voordeur
        show_info: false
      - type: picture-entity
        entity: camera.boris
        show_info: false
      - type: picture-entity
        entity: camera.foscam_camera
        show_info: false
#      - type: picture-glance
#        image: https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg?auto=compress&cs=tinysrgb&h=350
#        title: Woonkamer
#        entities:
#          - script.woonkamer
#          - script.woonkamer_nightlight
#          - script.woonkamer_bright
#          - script.woonkamer_super_bright
#          - script.woonkamer_off
#      - type: picture-glance
#        image: https://images.pexels.com/photos/15964/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350
#        title: Keuken
#        entities:
#          - script.keuken
#          - script.keuken_bright
#          - script.keuken_super_bright
#          - script.keuken_off
#      - type: entities
#        entities:
#          - input_number.keuken_hanglamp_brightness
#      - type: picture-glance
#        image: https://images.pexels.com/photos/573552/pexels-photo-573552.jpeg?auto=compress&cs=tinysrgb&h=350
#        title: Hal & Overlopen
#        entities:
#          - script.hal_en_overlopen
#          - script.hal_en_overlopen_nightlight
#          - script.hal_en_overlopen_bright
#          - script.hal_en_overlopen_super_bright
#          - script.hal_en_overlopen_off
#      - type: picture-glance
#        image: https://images.pexels.com/photos/547050/pexels-photo-547050.jpeg?auto=compress&cs=tinysrgb&h=350
#        title: Buiten
#        entities:
#          - script.buiten
#          - script.buiten_bright
#          - script.buiten_super_bright
#          - script.buiten_off
      - type: entities
        entities:
          - sensor.trash_today
          - sensor.trash_tomorrow
          - sensor.trash_gft
          - sensor.trash_restafval
          - sensor.trash_papier
          - sensor.trash_pmd
          - input_boolean.trash_moved
          - input_boolean.trash_reminder

  - icon: mdi:weather-cloudy
    title: Weather
    cards:
      - type: entities
        title: Thermostats
        entities:
          - input_number.woonkamer_nest_thermostat_temperature
          - sensor.hal_temperature
          - sensor.woonkamer_temperature
          - sensor.slaapkamer_boris_temperature
#          - climate.living_room
          - sensor.living_room_thermostat_temperature
          - sensor.living_room_thermostat_target
          - sensor.living_room_thermostat_operation_mode
          - sensor.living_room_thermostat_humidity
      - type: entities
        title: Forecast
        entities:
          - sensor.forecast_0
          - sensor.forecast_1
          - sensor.forecast_2
          - sensor.forecast_3
          - sensor.forecast_4
          - sensor.forecast_5
          - sensor.forecast_6
          - sensor.forecast_7
      - type: "iframe"
        aspect_ratio: 88%
        url: https://embed.windy.com/embed2.html?rainAccu,50.912,5.067,7

  - icon: mdi:cctv
    title: Cameras
    cards:
      - type: picture-entity 
        entity: camera.front_door_voordeur
        show_info: false
      - type: picture-entity
        entity: camera.boris
        show_info: false
      - type: picture-entity
        entity: camera.foscam_camera
        show_info: false

  - icon: mdi:play-circle-outline
    title: Media
    cards:
      - type: media-control
        entity: media_player.livingroom_tv
      - type: media-control
        entity: media_player.bedroom_tv
      - type: entities
        title: Plex Activity
        entities:
          - sensor.plex_activity

  - icon: mdi:power-plug
    title: Energy
    cards:
      - type: entities
        title: DSMR
        entities:
          - sensor.electricity_currently_delivered
          - sensor.electricity1
          - sensor.gas
      - type: custom:monster-card
        card:
          type: entities
          title: Huidige Energie Verbruikers
        filter:
          include: 
            - domain: light
              state: 'on'
      - type: entities
        title: HUE Sensors
        entities:
          - sensor.woonkamer_motion
          - sensor.switch_woonkamer
          - sensor.woonkamer_lux
          - sensor.hal_motion
          - sensor.switch_hal
          - sensor.hal_lux
      - type: entities
        title: Nest Protect
        entities:
          - sensor.living_room_nest_protect_co_status
          - sensor.living_room_nest_protect_smoke_status
          - sensor.living_room_nest_protect_battery_health
          - sensor.entryway_nest_protect_co_status
          - sensor.entryway_nest_protect_smoke_status
          - sensor.entryway_nest_protect_battery_health
          - sensor.upstairs_nest_protect_co_status
          - sensor.upstairs_nest_protect_smoke_status
          - sensor.upstairs_nest_protect_battery_health
      - type: entities
        title: Nest Hello
        entities:
          - binary_sensor.front_door_camera_voordeur_online
          - binary_sensor.front_door_camera_voordeur_motion_detected
          - binary_sensor.front_door_camera_voordeur_person_detected
          - binary_sensor.front_door_camera_voordeur_sound_detected

  - icon: mdi:network
    title: Network
    cards:
      - type: entities
        entities:
          - sensor.pihole_status
          - script.enable_pihole
          - input_select.pihole_time
          - sensor.pihole_ads_blocked_today
          - sensor.pihole_ads_percentage_blocked_today
          - sensor.pihole_dns_queries_cached
          - sensor.pihole_dns_queries_forwarded
          - sensor.pihole_dns_queries_today
          - sensor.pihole_dns_unique_clients
          - sensor.pihole_dns_unique_domains
          - sensor.pihole_domains_blocked
          - sensor.pihole_seen_clients
      - type: entities
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
      - type: entities
        entities:
          - sensor.samsung_printer
          - sensor.samsung_printer_toner_black
          - sensor.samsung_printer_tray_1
          - sensor.samsung_printer_output_tray_0
  - icon: mdi:settings
    title: Settings
    cards:
      - type: entities
        entities:
          - input_select.current_theme
      - type: custom:monster-card
        card:
          type: entities
          title: All Automations
        filter:
          include:
            - domain: automation
              state: 'on'

