resources:
  - url: /local/lovelace/custom-lovelace/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: /local/lovelace/tracker-card/tracker-card.js?v=0.3.2
    type: js
  - url: /local/lovelace/button-card/button-card.js?v=0.0.5
    type: module
  - url: /local/lovelace/mini-graph-card/mini-graph-card-bundle.js?v=0.4.3
    type: module
  - url: /local/lovelace/bar-card/bar-card.js?v=1.0.0
    type: js
  #- url: /local/lovelace/compact-custom-header/compact-custom-header.js?v=1.0.0b6
    #type: js

#x-compact-header: &compact-header
#- type: custom:compact-custom-header
#  header: true
#  menu: true
#  notification: true
#  voice: false
#  options: true
#  tabs: true
#  clock: notification
#  clock_format: 24
#  clock_am_pm: false
#  disable: true
#  yaml_mode: true

x-afval-images: &afval-images
- state_image:
    'gft': /local/mijnafvalwijzer/gft3.png
    'papier': /local/mijnafvalwijzer/papier3.png
    'restafval': /local/mijnafvalwijzer/rest3.png
    'pmd': /local/mijnafvalwijzer/plastic3.png
    'kerstbomen': /local/mijnafvalwijzer/kliko3.png
    'Geen': /local/mijnafvalwijzer/kliko3.png

name: Home
views:
  ################################################
  ## HOME
  ################################################
  - id: 0  # Automatically created id
    icon: mdi:home-assistant
    title: Home
    cards:
#      - type: markdown
#        content: >
#        ## Living room TV
      #- <<: *compact-header
      - id: 634f213a3d2f480faf0e4172ae4c0e4e  # Automatically created id
        type: entities
        show_header_toggle: false
        entities:
          - device_tracker.taipan5g
          - device_tracker.lieke_iphone

      - id: aedc813edd634881b238ec562b68643b  # Automatically created id
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.holiday_mode
          - input_boolean.automation_mode

#      - type: vertical-stack
#        cards:
#          - type: horizontal-stack
#            cards:
#              - type: light
#                entity: light.woonkamer
#                name: Living Room Lights
#              - type: light
#                entity: light.keuken
#                name: Kitchen Lights
#          - type: horizontal-stack
#            cards:
#              - type: light
#                entity: light.slaapkamer
#                name: Bedroom Lights
#              - type: light
#                entity: light.buiten
#                name: Outside Lights


      - id: 831a7ae69913420388b01fa8b4b3a77f  # Automatically created id
        type: entities
        show_header_toggle: false
        entities:
          - input_number.woonkamer_brightness
          # - input_number.hal_brightness
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'          
          - script.all_on
          # - script.all_on_bright
          # - script.all_on_super_bright
          - script.all_off
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - input_number.slaapkamer_hanglamp_brightness
          #- scene.slaapkamer_off
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - input_number.keuken_hanglamp_brightness
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          #- group.kerstmis
          - group.buiten
          #- switch.tuin
          - group.all_switches
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          #- switch.lex
          - light.slaapkamer_lex
          - switch.boris

      - type: vertical-stack
        cards:
        - id: dcb17306a9af4348ac01a6969ccb5ebe  # Automatically created id
          type: entities
          show_header_toggle: false
          entities:
            - input_number.woonkamer_nest_thermostat_temperature
            - climate.living_room
            - sensor.living_room_thermostat_target
            # - sensor.woonkamer_temperature
            - sensor.living_room_thermostat_humidity
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            - sensor.hal_temperature
            #- sensor.slaapkamer_boris_temperature

      # - type: vertical-stack
      #   cards:
      #   - type: horizontal-stack
      #     cards:
      #     - type: sensor
      #       entity: sensor.electricity_currently_delivered
      #   - type: horizontal-stack
      #     cards:
      #     - type: sensor
      #       entity: sensor.wasmachine_watts
      #       name: Wasmachine
      #     - type: sensor
      #       entity: sensor.droger_watts
      #       name: Droger

        # - type: custom:mini-graph-card
        #   name: DSMR
        #   icon: mdi:server
        #   entities:
        #     - sensor.wasmachine_watts
        #     - sensor.droger_watts
        #     - sensor.tuin_watts
        #     - sensor.tv_woonkamer_watts

        - id: 4ec3917eb0bb4154a6bc45c1ea3f7feb  # Automatically created id
          type: entities
          show_header_toggle: false
          entities:
            - sensor.electricity_currently_delivered
            - sensor.electricity1
            - sensor.gas
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            - sensor.tuin_watts
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            - sensor.tv_woonkamer_watts
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            #- sensor.wasmachine_watts
            #- sensor.wasmachine_this_week
            #- sensor.percent_wasmachine_weekly
            #- sensor.wasmachine_this_month
            #- sensor.percent_wasmachine_monthly
            - sensor.wasmachine_watts
            - sensor.wasmachine_status_time
            - sensor.wasmachine_status_value
            - type: divider
              style:
                height: 1px
                margin-left: auto
                margin-right: auto
                background: '#62717b'
            #- sensor.droger_watts
            #- sensor.droger_this_week
            #- sensor.percent_droger_weekly
            #- sensor.droger_this_month
            #- sensor.percent_droger_monthly
            - sensor.droger_watts
            - sensor.droger_status_time
            - sensor.droger_status_value

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: sensor.trash_today
                name: Vandaag
                <<: *afval-images
              - type: picture-entity
                entity: sensor.trash_tomorrow
                name: Morgen
                <<: *afval-images

          - type: glance
            entities:
             - entity: sensor.trash_gft_formatted
               name: GFT
             - entity: sensor.trash_papier_formatted
               name: Papier
             - entity: sensor.trash_pmd_formatted
               name: Plastic
             - entity: sensor.trash_restafval_formatted
               name: Restafval

          - type: entities
            show_header_toggle: false
            entities:
              - sensor.trash_next
              - input_boolean.trash_moved
              - input_boolean.trash_reminder

      - id: 274799b9eb634da6985a9cedd0d83017  # Automatically created id
        type: entities
        show_header_toggle: false
        entities:
          - input_boolean.meds_taken
          - input_boolean.meds_reminder

  ################################################
  ## CAMERAS/SECURITY
  ################################################
  - id: 2  # Automatically created id
    icon: mdi:cctv
    title: Cameras
    cards:
      #- <<: *compact-header

      - type: vertical-stack
        cards:
          - id: d8ccc6c98f794edab22d64dff6c78522  # Automatically created id
            type: picture-entity
            entity: camera.front_door
            show_name: false
            show_state: false
          # - type: conditional
          #   conditions:
          #     - entity: camera.boriscam
          #       state_not: ["off","unavailable"]
          #       #state_not: "unavailable"
          #   card:
          #     type: picture-entity
          #     entity: camera.boriscam
          #     show_name: false
          #     show_state: false
          # - id: f57bc50ad329439790f9ff6550f9a298  # Automatically created id
          #   type: picture-entity
          #   entity: camera.lexcam
          #   show_name: false
          #   show_state: false

  ################################################
  ## MEDIA
  ################################################
  - id: 3  # Automatically created id
    icon: mdi:play-circle-outline
    title: Media
    cards:
      #- <<: *compact-header

      - type: vertical-stack
        cards:
          #- type: entities
          #  show_header_toggle: false
          #  entities:
          #    - sensor.livingroom_tv_this_week
          #    - sensor.percent_livingroom_tv_weekly
          #    - sensor.livingroom_tv_this_month
          #    - sensor.percent_livingroom_tv_monthly
          - id: dc8acb366fa24c06914feb5d1018e7b5  # Automatically created id
            type: media-control
            entity: media_player.livingroom_tv

      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.living_room
            icon: mdi:google-home
            artwork: cover
            show_tts: google

      - type: vertical-stack
        cards:
          #- type: entities
          #  show_header_toggle: false
          #  entities:
          #    - sensor.bedroom_tv_this_week
          #    - sensor.percent_bedroom_tv_weekly
          #    - sensor.bedroom_tv_this_month
          #    - sensor.percent_bedroom_tv_monthly
          - id: e3df08f0e7dd44d3b2df12172ee60305  # Automatically created id
            type: media-control
            entity: media_player.bedroom_tv

      - id: 181bd7fa7ff4473db8188d295eea08a7  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Plex Activity
        entities:
          - sensor.plex_nas

  ################################################
  ## POWER
  ################################################
  - id: 4  # Automatically created id
    icon: mdi:power-plug
    title: Energy
    cards:
      #- <<: *compact-header

      - id: 52332e8847ee451e82d59429353094df  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Energy / Gas consumption
        entities:
          - sensor.electricity_currently_delivered
          - sensor.electricity1
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - sensor.gas

      # - type: sensor
      #   entity: sensor.electricity_currently_delivered
      #   name: DSMR - Huidig

      # - type: sensor
      #   entity: sensor.electricity1
      #   name: DSMR - Totaal Energie

      # - type: sensor
      #   entity: sensor.gas
      #   name: DSMR - Totaal Gas

      - id: c941976202ab41f8a9d3772ca5008dc7  # Automatically created id
        type: custom:monster-card
        card:
          type: entities
          show_header_toggle: false
          title: Huidige Energie Verbruikers
        filter:
          include:
            - domain: light
              state: 'on'

      - id: 52332e8847ee451e82d59429353094df  # Automatically created id
        type: entities
        show_header_toggle: false
        title: HUE Sensors
        entities:
          - sensor.woonkamer_motion
          - sensor.switch_woonkamer_lux
          - sensor.woonkamer_lux
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - sensor.hal_motion
          - sensor.switch_hal_lux
          - sensor.hal_lux

      - id: 8fc7f03aadb4410c9fbcf1ce1baec60f  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Nest Protect
        entities:
          - sensor.living_room_nest_protect_co_status
          - sensor.living_room_nest_protect_smoke_status
          - sensor.living_room_nest_protect_battery_health
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - sensor.entryway_nest_protect_co_status
          - sensor.entryway_nest_protect_smoke_status
          - sensor.entryway_nest_protect_battery_health
          - type: divider
            style:
              height: 1px
              margin-left: auto
              margin-right: auto
              background: '#62717b'
          - sensor.hallway_nest_protect_co_status
          - sensor.hallway_nest_protect_smoke_status
          - sensor.hallway_nest_protect_battery_health

      - id: 2f8e283fb9fc445cb3f5deaf3e33cf59  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Nest Hello
        entities:
          - binary_sensor.front_door_camera_online
          - binary_sensor.front_door_camera_motion_detected
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.front_door_camera_sound_detected

  ################################################
  ## NETWORK/INTERNET
  ################################################
  - id: 5  # Automatically created id
    icon: mdi:network
    title: Network
    cards:
      #- <<: *compact-header
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - id: 3fe5628fb1af4581ac183ca52e110db9  # Automatically created id
              type: entities
              show_header_toggle: false
              title: Pi-Hole
              entities:
                - sensor.pihole_status
                - script.enable_pihole
                - input_select.pihole_time
        - type: horizontal-stack
          cards:
            - type: custom:mini-graph-card
              entities:
                - sensor.pi_hole_ads_blocked_today
              name: Ads Blocked Today
              line_color: '#2980b9'
              line_width: 4
              hours_to_show: 24
            - type: custom:mini-graph-card
              entities:
                - sensor.pi_hole_ads_percentage_blocked_today
              name: Percentage Blocked
              line_color: '#2980b9'
              line_width: 4
              hours_to_show: 24
        - type: vertical-stack
          cards:
            - type: custom:bar-card
              entity: sensor.pi_hole_dns_queries_today
              title: DNS Queries Today
              title_position: inside
              align: split
              show_icon: true
              color: '#00ba6a'
              max: '30000'
            - type: custom:bar-card
              entity: sensor.pi_hole_domains_blocked
              title: Domains Blocked
              title_position: inside
              align: split
              show_icon: true
              max: '1000000'
              icon: mdi:cancel

      - type: custom:tracker-card
        title: Custom Card Updates
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

      - type: entities
        show_header_toggle: false
        title: HASS
        entities:
          - sensor.uptime
          - sensor.ha_installed_version
          - sensor.ha_current_version

      - type: entities
        show_header_toggle: false
        title: Synology
        entities:
          - sensor.synology_dsm_cpu_load_total
          - sensor.synology_dsm_memory_usage_real
          - sensor.synology_dsm_status_smart_sda
          - sensor.synology_dsm_status_smart_sdb
          - sensor.synology_dsm_status_smart_sdc
          - sensor.synology_dsm_temperature_sda
          - sensor.synology_dsm_temperature_sdb
          - sensor.synology_dsm_temperature_sdc
          - sensor.synology_dsm_volume_used_volume_1
          - sensor.synology_dsm_total_size_volume_1

      # - type: custom:mini-graph-card
      #   name: SERVER
      #   icon: mdi:server
      #   entities:
      #     - sensor.temperature_sda
      #     - sensor.temperature_sdb
      #     - sensor.temperature_sdc

      - id: 46c741ff7cfc4491a6b3712909c80469  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Internet
        entities:
          - sensor.external_ip
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping

      - id: a9b870b423a14aabaab904e4b37d6fc4  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Printer
        entities:
          - sensor.samsung_printer
          - sensor.samsung_printer_toner_black
#          - sensor.samsung_printer_tray_1
#          - sensor.samsung_printer_output_tray_0

  ################################################
  ## SETTINGS/TESTING
  ################################################
  - id: 6  # Automatically created id
    icon: mdi:settings
    title: Settings
    cards:
      #- <<: *compact-header

      - id: 7b93b97d36d449729c9e45775313200b  # Automatically created id
        type: entities
        show_header_toggle: false
        entities:
          - input_select.current_theme

      - id: 6442b597c98341909b8cf2d0a6adf750  # Automatically created id
        type: custom:monster-card
        card:
          type: entities
          show_header_toggle: false
          title: All Automations
        filter:
          include:
            - domain: automation
              state: 'on'
