- alias: "Slider - Keuken - Hanglamp - Set value"
  initial_state: on
  trigger:
  - platform: state
    entity_id: sensor.keuken_hanglamp_brightness
  - platform: state
    entity_id: light.keuken_hanglamp
    from: 'off'
    to: 'on'
  - platform: homeassistant
    event: start
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.keuken_hanglamp_brightness
      value: "{{ states.light.keuken_hanglamp.attributes.brightness | int }}"

- alias: "Switch - Keuken - Hanglamp - On"
  trigger:
  - platform: state
    entity_id: input_number.keuken_hanglamp_brightness
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.keuken_hanglamp
      brightness: "{{ trigger.to_state.state | int }}"


- alias: "Automation - All - Turn off"
  trigger:
  - platform: state
    entity_id: input_boolean.automation_mode
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.automation_mode
    state: 'on'
  action:
  - service: script.turn_on
    entity_id:
    - script.all_off
    - script.woonkamer_off
    - script.keuken_off
    - script.hal_en_overlopen_off
    - script.buiten_off


- alias: "Motion - Woonkamer - Morning on"
  trigger:
  - platform: state
    entity_id: sensor.woonkamer_motion
    to: 'True'
  - platform: state
    entity_id: sensor.hal_motion
    to: 'True'
  condition:
  - condition: time
    before: '10:00:00'
    after: '5:00:00'
  - condition: state
    entity_id: sensor.switch_woonkamer
    state: 'on'
  - condition: state
    entity_id: sensor.switch_hal
    state: 'on'
  - condition: state
    entity_id: input_boolean.automation_mode
    state: 'off'
  action:
  - service: script.turn_on
    entity_id:
      - script.woonkamer_bright
      - script.keuken_bright
      - script.buiten_bright


- alias: "Switch - Woonkamer - Daytime on"
  trigger:
  - platform: state
    entity_id: sensor.switch_woonkamer
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  - platform: state
    entity_id: input_boolean.woonkamer_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    before: '20:00:00'
    after: '5:00:00'
  - condition: state
    entity_id: sensor.switch_woonkamer
    state: 'on'
  - condition: state
    entity_id: input_boolean.automation_mode
    state: 'off'
  action:
  - service: script.turn_on
    entity_id:
    - script.woonkamer_bright
    - script.keuken_bright
    - script.buiten_bright


- alias: "Switch - Woonkamer - Evening on"
  trigger:
  - platform: state
    entity_id: sensor.switch_woonkamer
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  - platform: state
    entity_id: input_boolean.woonkamer_motion
    from: 'off'
    to: 'on'
  - platform: time
    at: '20:00:00'
  condition:
  - condition: time
    before: '05:00:00'
    after: '20:00:00'
  - condition: state
    entity_id: sensor.switch_woonkamer
    state: 'on'
  - condition: state
    entity_id: input_boolean.automation_mode
    state: 'off'
  action:
  - service: script.turn_on
    entity_id:
    - script.woonkamer
    - script.keuken
    - script.buiten  


- alias: "Switch - Woonkamer - Off"
  trigger:
  - platform: state
    entity_id: sensor.switch_woonkamer
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  - platform: state
    entity_id: input_boolean.woonkamer_motion
    from: 'on'
    to: 'off'
  - platform: time
    at: '00:00:00'
  condition:
  #- condition: state
  #  entity_id: media_player.lg_webos_smart_tv
  #  state: "off"
  - condition: state
    entity_id: input_boolean.automation_mode
    state: 'off'
  action:
  - service: script.turn_on
    entity_id:
    - script.all_off


- alias: "Switch - Woonkamer - When TV off"
  trigger:
  - platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: "off"
    for:
      minutes: 5
  condition:
  - condition: time
    before: '05:00:00'
    after: '21:00:00'
  action:
  - service: script.turn_on
    entity_id:
    - script.all_off 


- alias: "Motion - Hal en overlopen - Morning and evening on"
  trigger:
  - platform: state
    entity_id: sensor.hal_motion
    to: 'True'
  condition:
  - condition: or
    conditions:
    - condition: time
      before: '22:00:00'
      after: '20:00:00'
    - condition: time
      before: '08:00:00'
      after: '05:00:00'
  action:
  - service: script.turn_on
    entity_id:
    - script.hal_en_overlopen


- alias: "Motion - Hal en overlopen - Daytime on"
  trigger:
  - platform: state
    entity_id: sensor.hal_motion
    to: 'True'
  condition:
  - condition: and
    conditions:
    - condition: time
      before: '20:00:00'
      after: '08:00:00'
  action:
  - service: script.turn_on
    entity_id:
    - script.hal_en_overlopen_bright


- alias: "Motion - Hal en overlopen - Night on"
  trigger:
  - platform: state
    entity_id: sensor.hal_motion
    to: 'True'
  condition:
  - condition: and
    conditions:
    - condition: time
      before: '05:00:00'
      after: '22:00:00'
  action:
  - service: script.turn_on
    entity_id:
    - script.hal_en_overlopen_nightlight


- alias: "Motion - Hal en overlopen - Off"
  trigger:
  - platform: state
    entity_id: sensor.hal_motion
    to: 'False'
    for:
      minutes: 10
  action:
  - service: script.turn_on
    entity_id:
    - script.hal_en_overlopen_off
