- alias: "Woonkamer TV - Off"
  trigger:
  - platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: "off"
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.tv_status_woonkamer

- alias: "Woonkamer TV - On"
  trigger:
  - platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: "playing"
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.tv_status_woonkamer 
