- alias: 'Woonkamer Motion - True'
  trigger:
  - platform: state
    entity_id: sensor.woonkamer_motion
    to: 'True'
  condition:
  - condition: time
    after: '00:00:00'
    before: '05:00:00'
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.woonkamer_motion


- alias: 'Woonkamer Motion - False'
  trigger:
  - platform: state
    entity_id: sensor.woonkamer_motion
    to: 'False'
    for:
      minutes: 30
  condition:
  - condition: time
    after: '00:00:00'
    before: '05:00:00'
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.woonkamer_motion


- alias: 'Hal Motion - True'
  trigger:
  - platform: state
    entity_id: sensor.hal_motion
    to: 'True'
  condition:
  - condition: time
    after: '00:00:00'
    before: '05:00:00'
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.hal_motion


- alias: 'Hal Motion - False'
  trigger:
    - platform: state
      entity_id: sensor.hal_motion
      to: 'False'
      for:
        minutes: 30
  condition:
    - condition: time
      after: '00:00:00'
      before: '05:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.hal_motion
