- alias: 'Trash - One day before'
  trigger:
  - platform: time
    hours: 20
    minutes: 0
    seconds: 0
  condition:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{- (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_gft.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") -}}'
      - condition: template
        value_template: '{{- (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_restafval.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") -}}'
      - condition: template
        value_template: '{{- (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_pmd.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") -}}'
      - condition: template
        value_template: '{{- (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_papier.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") -}}'
#      - condition: template
#        value_template: '{{- (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_kerstbomen.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") -}}'
  action:
  - service: notify.family
    data_template:
      message: >-
        {% if (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_gft.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") %}
           Het is vandaag - {{ now().strftime("%Y-%m-%d") }}. De groene bak wordt geleegd op: {{ states.sensor.trash_gft.state }}!
        {% endif %}
        {% if (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_restafval.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") %}
           Het is vandaag - {{ now().strftime("%Y-%m-%d") }}. De grijze bak wordt geleegd op: {{ states.sensor.trash_restafval.state }}!
        {% endif %}
        {% if (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_pmd.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") %}
           Het is vandaag - {{ now().strftime("%Y-%m-%d") }}. Plastic wordt opgehaald op: {{ states.sensor.trash_pmd.state }}!
        {% endif %}
        {% if (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_papier.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") %}
           Het is vandaag - {{ now().strftime("%Y-%m-%d") }}. Papier wordt opgehaald op: {{ states.sensor.trash_papier.state }}!
        {% endif %}
#        {% if (now().strftime("%Y-%m-%d")) == (as_timestamp(strptime(states.sensor.trash_kerstbomen.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") %}
#           Het is vandaag - {{ now().strftime("%Y-%m-%d") }}. Kerstbomen worden opgehaald op: {{ states.sensor.trash_kerstbomen.state }}!
#        {% endif %}


###### NOTIFY IF FULL MOON
- alias: 'Notify - Full Moon'
  trigger:
  - platform: sun
    event: sunset
    offset: "01:00:00"
  condition:
  - condition: state
    entity_id: sensor.moon
    state: 'Full moon'
  action:
  - service: notify.ios_taipan5g
    data:
      title: "Hail Satan"
      message: "Rejoice, the full moon is upon us."


###### NEST PROTECT EMERGENCY NOTIFY
- alias: 'notify if nest protect is not ok'
  trigger:
  - platform: state
    entity_id: sensor.living_room_nest_protect_co_status,sensor.living_room_nest_protect_smoke_status
    to: 'emergency'
  - platform: state
    entity_id: sensor.entryway_nest_protect_co_status,sensor.entryway_nest_protect_smoke_status
    to: 'emergency'
  - platform: state
    entity_id: sensor.upstairs_nest_protect_co_status,sensor.upstairs_nest_protect_smoke_status
    to: 'emergency'
  action:
  - service: notify.ios_taipan5g
    data:
      message: 'Nest has detected Smoke or CO!!!'
  - service: notify.ios_lieke_iphone
    data:
      message: 'Nest has detected Smoke or CO!!'


##### NOTIFY LIEKE HOME
- alias: Alert when Lieke arrives home
  trigger:
  - platform: zone
    entity_id: device_tracker.lieke_iphone
    zone: zone.home
    event: enter
  action:
  - service: notify.ios_taipan5g
    data:
      message: 'Lieke is thuis!'

- alias: Alert when Lieke leaves home
  trigger:
  - platform: zone
    entity_id: device_tracker.lieke_iphone
    zone: zone.home
    event: leave
  action:
  - service: notify.ios_taipan5g
    data:
      message: 'Lieke is niet thuis!'

- alias: Lieke is 10 minutes from home
  trigger:
  - platform: numeric_state
    entity_id: sensor.lieke_distance_to_home
    value_template: '{{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] | int *60 }}'
    below: 600
  condition:
  - condition: state
    entity_id: 'device_tracker.lieke_iphone'
    state: 'not_home'
  action:
  - service: notify.ios_taipan5g
    data:
      message: 'Lieke is {{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] }} minutes from home'
      data:
        push:
          category: map
        action_data:
          shows_user_location: true
          latitude: "{{ trigger.to_state.attributes.latitude }}"
          longitude: "{{ trigger.to_state.attributes.longitude }}"


###### NOTIFY IF VACATION MODE
- alias: 'Notify Vacation Mode'
  trigger:
  - platform: state
    entity_id: input_boolean.vacation_mode
    from: 'off'
    to: 'on'
  action:
  - service: notify.ios_taipan5g
    data:
      message: "Vacation Mode is now {{ states('input_boolean.vacation_mode') }}!"


- alias: 'Turn Vacation Mode Off'
  trigger:
  - platform: state
    entity_id: input_boolean.vacation_mode
    from: 'on'
    to: 'off'
  action:
  - service: notify.ios_taipan5g
    data:
      message: "Vacation Mode is now {{ states('input_boolean.vacation_mode') }}!"
  - service: script.turn_off
    entity_id: script.flash_rgb_lights


##### VACATION ALARM NOTIFY
- alias: 'Motion Detection - Alert Start'
  trigger:
  - platform: state
    entity_id: sensor.woonkamer_motion
    to: 'True'
  - platform: state
    entity_id: sensor.hal_motion
    to: 'True'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: notify.ios_taipan5g
    data:
      message: 'Motion just detected at home!'
  - service: script.turn_on
    entity_id: script.flash_rgb_lights


- alias: 'Motion Detection - Alert Stop'
  trigger:
  - platform: state
    entity_id: sensor.woonkamer_motion
    to: 'False'
    for:
      minutes: 1
  - platform: state
    entity_id: sensor.hal_motion
    to: 'False'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: notify.ios_taipan5g
    data:
      message: 'Motion stopped at home!'
  - service: script.turn_off
    entity_id: script.flash_rgb_lights
