##########################################
##### Sensor
##########################################

- platform: mijnafvalwijzer
  postcode: !secret afvalwijzer_postcode
  huisnummer: !secret afvalwijzer_huisnummer

#- platform: rest
#  resource: ! secret afvalwijzer_json_url
#  name: Afvalwijzer info
#  value_template: >-
#    {% set now = as_timestamp(now()) %}
#    {% set today = now | timestamp_custom("%Y-%m-%d") %}
#    {% set trash = value_json.data.ophaaldagen.data[0].date %}
#    {{ trash }}

#  scan_interval: 3600

#- platform: template
#  sensors:
#    afval_vandaag:
#      friendly_name: "Afval vandaag"
#      value_template: >-
#        {% if is_state('sensor.afval_datum', 'vandaag') %}
#          {{states.sensor.afval_soort.state}}
#        {% else %}
#          Geen
#        {% endif %}

#- platform: scrape
#  resource: http://www.mijnafvalwijzer.nl/nl/<pcode>/<hnumber>
#  name: Afval Datum
#  select: ".firstDate"
#  scan_interval: 60

#- platform: scrape
#  resource: http://www.mijnafvalwijzer.nl/nl/<pcode>/<hnumber>
#  name: Afval Soort
#  select: ".firstWasteType"
#  scan_interval: 60

# Philips HUE - Sensors - Woonkamer
- platform: rest
  resource: !secret hue_woonkamer_temperature_sensor
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  scan_interval: 300
  unit_of_measurement: '°C'
  name: 'woonkamer_temperature'

- platform: rest
  resource: !secret hue_woonkamer_battery_sensor
  value_template: '{{ value_json.config.battery }}'
  scan_interval: 7200
  unit_of_measurement: '%'
  name: 'woonkamer_battery'

- platform: rest
  resource: !secret hue_woonkamer_motion_sensor
  value_template: '{{ value_json.state.presence }}'
  scan_interval: 1
  name: 'woonkamer_motion'

- platform: rest
  resource: !secret hue_woonkamer_lux_sensor
#  value_template: '{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}}'
  value_template: '{{ value_json.state.lightlevel }}'
  scan_interval: 30
  unit_of_measurement: 'Lux'
  name: 'woonkamer_lux'

# Philips HUE - Sensors - Hal en Overlopen
- platform: rest
  resource: !secret hue_hal_temperature_sensor
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  scan_interval: 300
  unit_of_measurement: '°C'
  name: 'hal_temperature'

- platform: rest
  resource: !secret hue_hal_battery_sensor
  value_template: '{{ value_json.config.battery }}'
  scan_interval: 7200
  unit_of_measurement: '%'
  name: 'hal_battery'

- platform: rest
  resource: !secret hue_hal_motion_sensor
  value_template: '{{ value_json.state.presence }}'
  scan_interval: 1
  name: 'hal_motion'

- platform: rest
  resource: !secret hue_hal_lux_sensor
  value_template: '{{ value_json.state.lightlevel }}'
  scan_interval: 30
  unit_of_measurement: 'Lux'
  name: 'hal_lux'

- platform: google_travel_time
  name: Bram Distance To Home
  api_key: !secret google_travel_time_key_bram
  origin: device_tracker.taipan5g
  destination: zone.home

- platform: google_travel_time
  name: Lieke Distance To Home
  api_key: !secret google_travel_time_key_lieke
  origin: device_tracker.lieke_iphone
  destination: zone.home

# Uptime Sensor
- platform: uptime

# Slimme Meter uitlezen
- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 2.2

# Current Time and Date
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'

# Dark Sky Weather
- platform: darksky
  api_key: !secret darksky_secret
  forecast: 7
  update_interval: 00:15
  monitored_conditions:
    - icon
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
    - uv_index

# Yr Weather
- platform: yr
  forecast: 48
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - humidity
    - fog

# Speedtest
- platform: speedtest
  server_id: 13218
  minute:
    - 0
  monitored_conditions:
    - ping
    - download
    - upload

# Nest Protect/Thermostat
- platform: nest
  monitored_conditions:
    - 'temperature'
    - 'target'
    - 'humidity'
    - 'mode'
    #  - 'last_ip'
    #  - 'local_ip'
    #  - 'last_connection'
    - 'weather_condition'
    - 'weather_temperature'
    - 'weather_humidity'
    - 'wind_speed'
    - 'wind_direction'
    - 'battery_level'
    - 'co_status'
    - 'smoke_status'

# Device Tracking + Activity Templates
- platform: template
  sensors:
    sunset_time:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
      friendly_name: "Sunset"
    sunrise_time:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
      friendly_name: "Sunrise"
    solar_angle:
      value_template: '{{ states.sun.sun.attributes.elevation }}'
      friendly_name: "Solar Angle"
      unit_of_measurement: degrees
    next_sunrise:
      friendly_name: "Next Sunrise"
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%d.%m.%Y %-H:%M") }}'
      icon_template: mdi:weather-sunset-up
    next_sunset:
      friendly_name: "Next Sunset"
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%d.%m.%Y %-H:%M") }}'
      icon_template: mdi:weather-sunset-down
    day_of_year:
      friendly_name: "Day Number"
      value_template: '{{ now().strftime("%j") }}'
    week_of_year:
      friendly_name: "Week Number"
      value_template: '{{ now().strftime("%U") }}'
#    trash_gft_date:
#      friendly_name: "Groene bak"
#      value_template: '{{- (as_timestamp(strptime(states.sensor.trash_restafval.state, "%Y-%m-%d")) - (1 * 86400 )) | timestamp_custom("%Y-%m-%d") -}}' 
#    trash_restafval_date:
#      friendly_name: "Grijze bak"
#      value_template: '{{ as_timestamp(states.sensor.trash_restafval.state) | timestamp_custom("%Y-%m-%d") }}'
#    trash_papier_date:
#      friendly_name: "Papier"
#      value_template: '{{ as_timestamp(states.sensor.trash_papier.state) | timestamp_custom("%Y-%m-%d") }}'
#    trash_pmd_date:
#      friendly_name: "Plastic"
#      value_template: '{{ as_timestamp(states.sensor.trash_pmd.state) | timestamp_custom("%Y-%m-%d") }}'
    keuken_hanglamp_brightness:
      value_template: >-
        {%- if is_state('light.keuken_hanglamp', 'on') -%}
          {{ states.light.keuken_hanglamp.attributes.brightness | int }}
        {%- else -%}
          127
        {%- endif -%}
    woonkamer_nest_thermostat_temperature:
      value_template: "{{ states('input_number.woonkamer_nest_thermostat_temperature') | float }}"
    woonkamer_nest_thermostat_target_vs_current:
      value_template: >-
        {%- if states('sensor.living_room_thermostat_temperature') | float != states('sensor.living_room_thermostat_target') | float -%}
          true
        {%- else -%}
          false
        {%- endif -%}
    woonkamer_nest_thermostat_temperature_changed:
      value_template: >-
        {%- if states('input_number.woonkamer_nest_thermostat_temperature') | float != states('sensor.living_room_thermostat_target') | float -%}
          true
        {%- else -%}
          false
        {%- endif -%}
    switch_hal:
      value_template: >-
        {%- if states('sensor.hal_lux') | int < 20000 -%}
          on
        {%- else -%}
          off
        {%- endif -%}
    switch_woonkamer:
      value_template: >-
        {%- if states('sensor.woonkamer_lux') | int < 14000 -%}
          on
        {%- else -%}
          off
        {%- endif -%}
    vacation_mode:
      value_template: >-
        {%- if is_state('input_boolean.vacation_mode', 'on') -%}
          enabled
        {%- else -%}
          disabled
        {%- endif -%}
#    trash_test:
#      value_template: >-
#        {% states.sensor.afvalwijzer_info.attributes.data.ophaaldagen.data %}

# Moon
- platform: moon

- platform: plex
  name: plex_activity
  host: !secret plex_host
  port: !secret plex_port
  username: !secret plex_username
  password: !secret plex_password
  token: !secret plex_token
