################################################
## Packages / Cameras
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'cameras'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Camera
################################################
camera:
  - platform: mjpeg
    name: Boris
    still_image_url: !secret camera_boris_image_url
    mjpeg_url: !secret camera_boris_mjpeg_url
    username: !secret camera_boris_username
    password: !secret camera_boris_password

################################################
## Group
################################################
group:
  slaapkamer_boris_camera:
    name: "Camera Boris"
    entities:
      - camera.boris
  frontdoor_camera:
    name: "Camera Voordeur"
    entities:
      - camera.front_door_voordeur

################################################
## Automation
################################################
#automation:
#  - id: notify_camera_pictures
#    alias: 'Notify camera pictures'
#    initial_state: 'on'
#    trigger:
#     - platform: time
#       minutes: '/2'
#       seconds: 00
#    action:
#    - service: notify.bram
#      data_template:
#        message: "Check Camera."
#        data:
#          photo:
#            - url: !secret camera_boris_image_url
#              caption: "Test"