################################################
## Packages / Dsmr
################################################
homeassistant:
  customize:
    sensor.electricity_currently_delivered:
      friendly_name: Huidig verbruik electriciteit
      icon: mdi:power-plug
    sensor.electricity1:
      friendly_name: Verbruik vandaag electriciteit
      icon: mdi:power-plug
    sensor.gas:
      friendly_name: Verbruik vandaag gas
      icon: mdi:power-plug

################################################
## Sensor
################################################
sensor:
  - platform: rest
    name: electricity_currently_delivered
    resource: !secret dsmr_current
    unit_of_measurement: 'W'
    value_template: '{{ value_json["results"][0].electricity_currently_delivered | multiply(1000) | round(0) }}'
    headers:
      X-AUTHKEY: !secret dsmr_token

  - platform: rest
    name: electricity1
    resource: !secret dsmr_today
    unit_of_measurement: 'kWh'
    value_template: '{{ value_json.electricity1 | round(3) }}'
    headers:
      X-AUTHKEY: !secret dsmr_token

  - platform: rest
    name: gas
    resource: !secret dsmr_today
    unit_of_measurement: 'm³'
    value_template: '{{ value_json.gas | round(3) }}'
    headers:
      X-AUTHKEY: !secret dsmr_token

#sensor:
#  - platform: dsmr
#    port: /dev/ttyUSB0
#    dsmr_version: 2.2
