################################################
## Packages / HTTP
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'http'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## HTTP
################################################
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3  