################################################
## Packages / Speedtest
################################################
homeassistant:

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

################################################
## Sensor
################################################
sensor:
  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: '{{ value }}'
    scan_interval: 14400

################################################
## Automation
################################################
automation:
  - alias: "Speedtest - Update sensor"
    initial_state: 'on'
    trigger:
    - platform: time_pattern
      minutes: '/15'
      seconds: 00
    action:
    - service: speedtestdotnet.speedtest