################################################
## Packages / Speedtest
################################################
homeassistant:

speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload
################################################
## Sensor
################################################
sensor:
  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: '{{ value }}'
    scan_interval: 14400