################################################
## Packages / Speedtest
################################################
homeassistant:

################################################
## Sensor
################################################
sensor:
  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: '{{ value }}'
    scan_interval: 14400