################################################
## Packages / Lights
################################################
homeassistant:
  customize:
    group.all_lights:
      control: hidden
    script.all_off:
      friendly_name: All Lights Off
      icon: mdi:flash
    script.woonkamer_off:
      friendly_name: Woonkamer
      icon: mdi:flashlight-off
    script.keuken_off:
      friendly_name: Keuken
      icon: mdi:flashlight-off
    script.hal_en_overlopen_off:
      friendly_name: Hal en Overlopen
      icon: mdi:flashlight-off
    group.buiten:
      friendly_name: Buiten
    script.buiten_off:
      friendly_name: Buiten
      icon: mdi:flashlight-off
    switch.all_on:
      friendly_name: All lights
      icon: mdi:flash
    script.all_on:
      friendly_name: All Lights On
      icon: mdi:flash
    script.all_on_bright:
      friendly_name: All Lights Bright
      icon: mdi:flash
    script.all_on_super_bright:
      friendly_name: All Lights Super Bright
      icon: mdi:flash
    script.woonkamer:
      friendly_name: Woonkamer
      icon: mdi:flashlight
    script.keuken:
      friendly_name: Keuken
      icon: mdi:flashlight
    script.buiten:
      friendly_name: Buiten
      icon: mdi:flashlight
    sensor.motion_woonkamer:
      friendly_name: Woonkamer Motion
      icon: mdi:run-fast
    sensor.motion_hal:
      friendly_name: Hal Motion
      icon: mdi:run-fast

################################################
## Hue
################################################
hue:
  bridges:
    - host: !secret philips_hue_host
      allow_unreachable: true
      allow_hue_groups: true

################################################
## Input Number
################################################
input_number:
  keuken_hanglamp_brightness:
    initial: 0
    min: 0
    max: 100
    step: 5
    icon: mdi:brightness-auto

input_boolean:
  automation_mode:
    name: "Automation Mode"
    initial: off
    icon: mdi:human-male-female
  vacation_mode:
    name: "Vacation Mode"
    initial: off
    icon: mdi:human-male-female
  woonkamer_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  hal_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female

################################################
## Sensor
################################################
sensor:
  - platform: hue
    ip_address: !secret philips_hue_host
    token: !secret philips_hue_token

  - platform: template
    sensors:
      woonkamer_temperature:
        friendly_name: 'Woonkamer temperatuur'
        value_template: '{{states.sensor.motion_woonkamer.attributes.temperature}}'
        unit_of_measurement: °C
      woonkamer_lux:
        friendly_name: 'Woonkamer Lux'
        value_template: '{{states.sensor.motion_woonkamer.attributes.lx}}'
        unit_of_measurement: lux
      hal_temperature:
        friendly_name: 'Hal temperatuur'
        value_template: '{{states.sensor.motion_hal.attributes.temperature}}'
        unit_of_measurement: °C
      hal_lux:
        friendly_name: 'Hal Lux'
        value_template: '{{states.sensor.motion_hal.attributes.lx}}'
        unit_of_measurement: lux

  - platform: template
    sensors:
      keuken_hanglamp_brightness:
        friendly_name: 'Keuken Hanglamp'
        value_template: >-
          {%- if is_state('light.keuken_hanglamp', 'on') -%}
            {{ states.light.keuken_hanglamp.attributes.brightness | int / 2.55 }}
          {%- endif -%}
        unit_of_measurement: '%'
      switch_hal_lux:
        value_template: >-
          {%- if states('sensor.hal_lux') | int < 6000 -%} on
          {%- else -%} off
          {%- endif -%}
      switch_woonkamer_lux:
        value_template: >-
          {%- if states('sensor.woonkamer_lux') | int < 12000 -%} on
          {%- else -%} off
          {%- endif -%}

################################################
## Automation
################################################
automation:

  # KEUKEN
  - alias: "Slider - Keuken - Hanglamp - Set value"
    initial_state: on
    trigger:
    - platform: state
      entity_id: sensor.keuken_hanglamp_brightness
    - platform: state
      entity_id: light.keuken_hanglamp
      from: 'off'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.keuken_hanglamp_brightness
        value: >-
          {%- if states.light.keuken_hanglamp.attributes.brightness is defined -%}
            {{ trigger.to_state.state | int }}
          {%- else -%}
            0
          {%- endif -%}

  - alias: "Switch - Keuken - Hanglamp - On"
    trigger:
    - platform: state
      entity_id: input_number.keuken_hanglamp_brightness
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.keuken_hanglamp
        brightness: "{{ trigger.to_state.state | int }}"

  # FRONTDOOR
  - alias: "Motion and Person - Doorbel - Turn On/Off"
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_person_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_motion_detected
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_person_detected
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      before: '05:00:00'
      after: '00:00:00'
    action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('binary_sensor.front_door_camera_voordeur_motion_detected', 'on') -%}
          scene.buiten_bright
          {%- else -%}
          script.buiten_off
          {%- endif -%}

  # GENERAL
  - alias: "General lights On/Off"
    trigger:
    - platform: time
      minutes: '/10'
      seconds: 00
    - platform: state
      entity_id: sensor.switch_woonkamer_lux
      from: 'off'
      to: 'on'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.switch_woonkamer_lux
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.motion_hal
      to: 'on'
    - platform: state
      entity_id: sensor.motion_woonkamer
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.automation_mode
      state: 'off'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if (is_state('sensor.switch_woonkamer_lux', 'on') and is_state('sensor.switch_hal_lux', 'on')) and states('sensor.time_of_day_short') in ['daytime'] -%}
          script.woonkamer, script.keuken
          {%- elif (is_state('sensor.switch_woonkamer_lux', 'on') and is_state('sensor.switch_hal_lux', 'on')) and states('sensor.time_of_day_short') in ['early evening','evening'] -%}
          script.woonkamer, script.keuken, script.buiten
          #{%- elif (is_state('sensor.motion_woonkamer', 'on') or is_state('sensor.motion_hal', 'on')) and states('sensor.time_of_day_short') in ['night'] -%}
          #script.woonkamer, script.keuken
          {%- elif is_state('media_player.livingroom_tv', 'off') and states('sensor.time_of_day_short') in ['evening','night'] -%}
          script.all_off
          {%- elif is_state('sensor.switch_woonkamer_lux', 'off') and states('sensor.time_of_day_short') in ['daytime','early evening'] -%}
          script.all_off
          {%- endif -%}

  # HAL & OVERLOPEN
  - alias: "Hal en overlopen On/Off"
    trigger:
    - platform: state
      entity_id: sensor.motion_hal
      to: 'on'
    - platform: state
      entity_id: sensor.motion_hal
      to: 'off'
      for:
        minutes: 10
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('sensor.switch_hal_lux', 'on') and is_state('sensor.motion_hal', 'on')-%}
          script.hal_en_overlopen
          {%- else -%}
          script.hal_en_overlopen_off
          {%- endif -%}

# KIDS NACHTLAMP
  - alias: 'Lights Lex On/Off'
    trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
    - platform: sun
      event: sunrise
      offset: '+00:00:00'
    action:
    - service_template: >-
        {%- if trigger.event == "sunset" -%}
        homeassistant.turn_on
        {%- elif trigger.event == "sunrise" -%}
        homeassistant.turn_off
        {%- endif -%}
      entity_id: group.kinderen

################################################
## Group
################################################
group:
  buiten:
    - light.buitenachter
    - light.buitenvoor
    - switch.smartplug2
  beneden:
    - light.woonkamer
    - light.keuken
  kinderen:
    - switch.smartplug4
    - switch.smartplug7
  hal_en_overlopen:
    - light.hal_en_overlopen

################################################
## Script
################################################
script:
# ALL
  all_on:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_general
    - service: scene.turn_on
      entity_id: scene.keuken_general
    - service: scene.turn_on
      entity_id: scene.buiten_general

  all_on_bright:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_bright
    - service: scene.turn_on
      entity_id: scene.keuken_bright
    - service: scene.turn_on
      entity_id: scene.hal_en_overlopen_bright

  all_on_super_bright:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_super_bright
    - service: scene.turn_on
      entity_id: scene.keuken_super_bright
    - service: scene.turn_on
      entity_id: scene.hal_en_overlopen_super_bright

  all_off:
    sequence:
    - service: scene.turn_on
      entity_id: scene.all_off

# WOONKAMER
  woonkamer:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.woonkamer_
          {%- if states('sensor.time_of_day_short') in ['daytime'] -%}bright
          {%- else -%}general
          {%- endif -%}

  woonkamer_off:
    sequence:
    - service: light.turn_off
      entity_id: light.woonkamer

# KEUKEN
  keuken:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.keuken_
          {%- if states('sensor.time_of_day_short') in ['daytime'] -%}bright
          {%- else -%}general
          {%- endif -%}

  keuken_off:
    sequence:
    - service: light.turn_off
      entity_id: light.keuken

# HAL EN OVERLOPEN
  hal_en_overlopen:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.hal_en_overlopen_
          {%- if states('sensor.time_of_day_short') in ['evening'] -%}evening
          {%- elif states('sensor.time_of_day_short') in ['night'] -%}night
          {%- else -%}general
          {%- endif -%}

  hal_en_overlopen_off:
    sequence:
    - service: light.turn_off
      entity_id: light.hal_en_overlopen

# BUITEN
  buiten:
    sequence:
    - service: scene.turn_on
      entity_id: scene.buiten_general

  buiten_off:
    sequence:
    - service: homeassistant.turn_off
      entity_id: group.buiten
