################################################
## Packages / Lights Holiday
################################################
homeassistant:

################################################
## Inputs
################################################
input_boolean:
  holiday_mode:
    name: "Holiday Mode"
    initial: off
    icon: mdi:human-male-female

################################################
## Script
################################################
script:
  flash_rgb_lights:
    sequence:
    - alias: 'flash rgb lights on'
      service: light.turn_on
      entity_id:
      - group.all_lights
      data:
        rgb_color: [98,19,0]
        brightness: 255
    - delay:
        seconds: 1
    - alias: 'flash rgb lights off'
      service: light.turn_off
      entity_id:
      - group.all_lights
    - delay:
        seconds: 1
    - alias: 'loop flash rgb lights'
      service: script.turn_off
      entity_id: script.flash_rgb_lights
    - alias: 'loop flash rgb lights'
      service: script.turn_on
      entity_id: script.flash_rgb_lights

################################################
## Automation
################################################
automation:
  - alias: 'Turn Holiday Mode On'
    trigger:
    - platform: state
      entity_id: input_boolean.holiday_mode
      from: 'off'
      to: 'on'
    action:
    - service: notify.bram
      data:
        message: "Holiday Mode is now {{ states('input_boolean.holiday_mode') }}!"
    - service: script.turn_off
      entity_id: script.flash_rgb_lights
    - service: homeassistant.turn_off
      entity_id: group.all_switches

  - alias: 'Turn Holiday Mode Off'
    trigger:
    - platform: state
      entity_id: input_boolean.holiday_mode
      from: 'on'
      to: 'off'
    action:
    - service: notify.bram
      data:
        message: "Holiday Mode is now {{ states('input_boolean.holiday_mode') }}!"
    - service: script.turn_off
      entity_id: script.flash_rgb_lights

  - alias: "Lights On/Off - Holiday"
    trigger:
    - platform: state
      entity_id: sensor.time_of_day_short
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'on'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('sensor.switch_woonkamer_lux', 'on') and states('sensor.time_of_day_short') in ['early evening','evening'] -%}
            script.woonkamer, script.keuken, script.buiten
          {%- else -%}
            script.all_off
          {%- endif -%}

  - alias: 'Motion Detection - Alert Start'
    trigger:
    - platform: state
      entity_id: sensor.woonkamer_motion
      to: 'True'
    - platform: state
      entity_id: sensor.hal_motion
      to: 'True'
    condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'on'
    action:
    - service: notify.bram
      data:
        message: 'Motion just detected at home!'
    - service: script.turn_on
      entity_id: script.flash_rgb_lights

  - alias: 'Motion Detection - Alert Stop'
    trigger:
    - platform: state
      entity_id: sensor.woonkamer_motion
      to: 'False'
      for:
        minutes: 1
    - platform: state
      entity_id: sensor.hal_motion
      to: 'False'
      for:
        minutes: 1
    condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: 'on'
    action:
    - service: notify.bram
      data:
        message: 'Motion stopped at home!'
    - service: script.turn_off
      entity_id: script.flash_rgb_lights
