################################################
## Packages / Lights
################################################
homeassistant:
  customize:
    group.all_lights:
      control: hidden
    script.all_off:
      friendly_name: All Lights Off
      icon: mdi:flash
    script.woonkamer_off:
      friendly_name: Woonkamer
      icon: mdi:flashlight-off
    script.keuken_off:
      friendly_name: Keuken
      icon: mdi:flashlight-off
    script.hal_en_overlopen_off:
      friendly_name: Hal en Overlopen
      icon: mdi:flashlight-off
    group.buiten:
      friendly_name: Buiten
    group.buiten_switches:
      friendly_name: Buiten Switches
    group.all_switches:
      friendly_name: Alle Switches
    light.slaapkamer_lex:
      friendly_name: Verlichting Lex
    light.buiten:
      friendly_name: Buiten
      icon: mdi:pine-tree
    light.woonkamer:
      icon: mdi:sofa
    light.keuken:
      icon: mdi:stove
    light.slaapkamer:
        icon: mdi:hotel
    script.buiten_off:
      friendly_name: Buiten
      icon: mdi:flashlight-off
    switch.all_on:
      friendly_name: All lights
      icon: mdi:flash
    script.all_on:
      friendly_name: All Lights On
      icon: mdi:flash
    script.all_on_bright:
      friendly_name: All Lights Bright
      icon: mdi:flash
    script.all_on_super_bright:
      friendly_name: All Lights Super Bright
      icon: mdi:flash
    script.woonkamer:
      friendly_name: Woonkamer
      icon: mdi:flashlight
    script.keuken:
      friendly_name: Keuken
      icon: mdi:flashlight
    sensor.woonkamer_motion:
      friendly_name: Woonkamer Motion
      icon: mdi:run-fast
    sensor.hal_motion:
      friendly_name: Hal Motion
      icon: mdi:run-fast
    sensor.woonkamer_temperature:
      friendly_name: Woonkamer Temperatuur
    sensor.hal_temperature:
      friendly_name: Hal Temperatuur
    sensor.woonkamer_lux:
      friendly_name: Woonkamer Lux
    sensor.hal_lux:
      friendly_name: Hal Lux
    sensor.switch_woonkamer_lux:
      friendly_name: Woonkamer Lux Switch
    sensor.switch_hal_lux:
      friendly_name: Hal Lux Switch
    input_number.woonkamer_brightness:
      friendly_name: Woonkamer
    input_number.hal_brightness:
      friendly_name: Hal
    input_number.keuken_hanglamp_brightness:
      friendly_name: Keuken Hanglamp
    input_number.slaapkamer_hanglamp_brightness:
      friendly_name: Slaapkamer

################################################
## Hue
################################################
hue:
  bridges:
    - host: !secret philips_hue_host
      allow_unreachable: true
      allow_hue_groups: true

################################################
## Inputs
################################################
input_number:
  woonkamer_brightness:
    initial: 127
    min: 0
    max: 254
    step: 10
  hal_brightness:
    initial: 127
    min: 0
    max: 254
    step: 10
  keuken_hanglamp_brightness:
    initial: 127
    min: 0
    max: 254
    step: 10
  slaapkamer_hanglamp_brightness:
    initial: 127
    min: 0
    max: 254
    step: 10

input_boolean:
  automation_mode:
    name: "Automation Mode"
    initial: off
    icon: mdi:human-male-female
  light_automation_override:
    name: "Light Automation Override"
    initial: off
    icon: mdi:human-male-female
  woonkamer_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  hal_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female

################################################
## Sensor
################################################
sensor:
  # Philips HUE - Sensors - Woonkamer
  - platform: rest
    resource: !secret hue_woonkamer_temperature_sensor
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    scan_interval: 300
    unit_of_measurement: '°C'
    name: 'woonkamer_temperature'
  - platform: rest
    resource: !secret hue_woonkamer_battery_sensor
    value_template: '{{ value_json.config.battery }}'
    scan_interval: 1800
    unit_of_measurement: '%'
    name: 'woonkamer_battery'
  - platform: rest
    resource: !secret hue_woonkamer_motion_sensor
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: 'woonkamer_motion'
  - platform: rest
    resource: !secret hue_woonkamer_lux_sensor
  #  value_template: '{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}}'
    value_template: '{{ value_json.state.lightlevel }}'
    scan_interval: 30
    unit_of_measurement: 'Lux'
    name: 'woonkamer_lux'

  - platform: rest
    resource: !secret hue_remote_1
    value_template: '{{ value_json.state.buttonevent }}'
    name: 'Hue Switch Woonkamer'
    scan_interval: 1
    verify_ssl: false
  - platform: rest
    resource: !secret hue_remote_1
    value_template: '{{ value_json.state.lastupdated }}'
    name: 'Hue Switch Woonkamer Updated'
    scan_interval: 1
    verify_ssl: false

  - platform: rest
    resource: !secret hue_remote_2
    value_template: '{{ value_json.state.buttonevent }}'
    name: 'Hue Switch Slaapkamer'
    scan_interval: 1
    verify_ssl: false
  - platform: rest
    resource: !secret hue_remote_2
    value_template: '{{ value_json.state.lastupdated }}'
    name: 'Hue Switch Slaapkamer Updated'
    scan_interval: 1
    verify_ssl: false


  # Philips HUE - Sensors - Hal en Overlopen
  - platform: rest
    resource: !secret hue_hal_temperature_sensor
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    scan_interval: 300
    unit_of_measurement: '°C'
    name: 'hal_temperature'
  - platform: rest
    resource: !secret hue_hal_battery_sensor
    value_template: '{{ value_json.config.battery }}'
    scan_interval: 1800
    unit_of_measurement: '%'
    name: 'hal_battery'
  - platform: rest
    resource: !secret hue_hal_motion_sensor
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: 'hal_motion'
  - platform: rest
    resource: !secret hue_hal_lux_sensor
    value_template: '{{ value_json.state.lightlevel }}'
    scan_interval: 30
    unit_of_measurement: 'Lux'
    name: 'hal_lux'

  - platform: template
    sensors:
      switch_hal_lux:
        value_template: >-
          {%- if states('sensor.hal_lux') | int < 6000 -%} on
          {%- else -%} off
          {%- endif -%}
      switch_woonkamer_lux:
        value_template: >-
          {%- if states('sensor.woonkamer_lux') | int < 12000 -%} on
          {%- else -%} off
          {%- endif -%}

################################################
## Automation
################################################
automation:
  # WOONKAMER
  - alias: "Switch - Woonkamer - On"
    trigger:
    - platform: state
      entity_id: input_number.woonkamer_brightness
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.woonkamer
        brightness: "{{ trigger.to_state.state | int }}"
    - service: light.turn_on
      data_template:
        entity_id: light.keuken
        brightness: "{{ trigger.to_state.state | int }}"

  - alias: "Switch - Woonkamer - Hanglamp - Off"
    trigger:
    - platform: numeric_state
      entity_id: input_number.woonkamer_brightness
      below: 1
    action:
    - service: light.turn_off
      data_template:
        entity_id: light.woonkamer
    - delay:
        seconds: 1
    - service: light.turn_off
      data_template:
        entity_id: light.keuken

  # HAL
  # - alias: "Switch - Hal - On"
  #   trigger:
  #   - platform: state
  #     entity_id: input_number.hal_brightness
  #   action:
  #   - service: light.turn_on
  #     data_template:
  #       entity_id: light.hal_bg
  #       brightness: "{{ trigger.to_state.state | int }}"

  # - alias: "Switch - hal - Hanglamp - Off"
  #   trigger:
  #   - platform: numeric_state
  #     entity_id: input_number.hal_brightness
  #     below: 1
  #   action:
  #   - service: light.turn_off
  #     data_template:
  #       entity_id: light.hal_bg

  # KEUKEN
  - alias: "Switch - Keuken - Hanglamp - On"
    trigger:
    - platform: state
      entity_id: input_number.keuken_hanglamp_brightness
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.keuken_hanglamp
        brightness: "{{ trigger.to_state.state | int }}"

  - alias: "Switch - Keuken - Hanglamp - Off"
    trigger:
    - platform: numeric_state
      entity_id: input_number.keuken_hanglamp_brightness
      below: 1
    action:
    - service: light.turn_off
      data_template:
        entity_id: light.keuken_hanglamp

  # SLAAPKAMER
  - alias: "Switch - Slaapkamer - Hanglamp - On"
    trigger:
    - platform: state
      entity_id: input_number.slaapkamer_hanglamp_brightness
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.slaapkamer
        brightness: "{{ trigger.to_state.state | int }}"

  - alias: "Switch - Slaapkamer - Hanglamp - Off"
    trigger:
    - platform: numeric_state
      entity_id: input_number.slaapkamer_hanglamp_brightness
      below: 1
    action:
    - service: light.turn_off
      data_template:
        entity_id: light.slaapkamer

  # FRONTDOOR
  - alias: "Motion and Person - Doorbel - Turn On/Off"
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_person_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_motion_detected
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_person_detected
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      before: '05:00:00'
      after: '22:00:00'
    action:
    #- service: notify.bram
    #  data_template:
    #    message: '{{ trigger.to_state.attributes.friendly_name }} triggerd to {{ trigger.to_state.state }} at {{ states("sensor.time") }}!'
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('binary_sensor.front_door_camera_voordeur_motion_detected', 'on') -%}
            script.buiten
          {%- else -%}
            script.buiten_off
          {%- endif -%}

  # GENERAL
  - alias: "General lights On/Off"
    trigger:
    - platform: state
      entity_id: sensor.hal_motion
      to: 'True'
    - platform: state
      entity_id: sensor.woonkamer_motion
      to: 'True'
    condition:
    - condition: state
      entity_id: input_boolean.automation_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.light_automation_override
      state: 'off'
    - condition: template
      value_template: "{{ states('sensor.time_of_day') in ['early morning'] }}"
    action:
    - service: script.turn_on
      entity_id: script.woonkamer, script.keuken

  # - alias: "General lights off - 1000"
  #   trigger:
  #     platform: time
  #     at: '10:00:00'
  #   condition:
  #   - condition: state
  #     entity_id: input_boolean.automation_mode
  #     state: 'off'
  #   - condition: state
  #     entity_id: input_boolean.holiday_mode
  #     state: 'off'
  #   - condition: state
  #     entity_id: input_boolean.light_automation_override
  #     state: 'off'
  #   action:
  #   - service: script.turn_on
  #     entity_id: script.all_off

  # GENERAL - 1002 aan / 2002 + / 3002 - / 4002 off
  - alias: "Woonkamer On/Off - Lux trigger"
    trigger:
    - platform: state
      entity_id: sensor.switch_woonkamer_lux
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.automation_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.light_automation_override
          state: 'off'
        - condition: template
          value_template: "{{ (as_timestamp(now())-as_timestamp(states.sensor.switch_woonkamer_lux.last_changed)) < 300 }}"
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('sensor.switch_woonkamer_lux', 'on') -%}
            script.woonkamer, script.keuken, script.buiten
          {%- else -%}
            script.all_off
          {%- endif -%}

  - alias: "Woonkamer On/Off - Hue Dimmer Switch trigger"
    trigger:
    - platform: state
      entity_id: sensor.hue_switch_woonkamer
    - platform: state
      entity_id: sensor.hue_switch_woonkamer_updated
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('sensor.hue_switch_woonkamer', '1002') -%}
            script.woonkamer, script.keuken, script.buiten, script.hal_en_overlopen
          {%- elif is_state('sensor.hue_switch_woonkamer', '4002') -%}
            script.all_off, script.hal_en_overlopen_off
          {%- endif -%}
    - service_template: >-
        {%- if is_state('sensor.hue_switch_woonkamer', '1002') -%}
          homeassistant.turn_on
        {%- elif is_state('sensor.hue_switch_woonkamer', '4002') -%}
          homeassistant.turn_off
        {%- endif -%}
      entity_id: input_boolean.light_automation_override

  - alias: "Woonkamer On/Off - TV trigger"
    trigger:
    - platform: state
      entity_id: media_player.livingroom_tv
      from: 'on'
      to: 'off'
      for:
        minutes: 120
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.automation_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.light_automation_override
          state: 'off'
        - condition: state
          entity_id: media_player.livingroom_tv
          state: 'off'
        - condition: template
          value_template: "{{ states('sensor.time_of_day_short') in ['evening','night'] }}"
    action:
    - service: script.turn_on
      entity_id: script.all_off

  # HAL & OVERLOPEN
  - alias: "Hal en overlopen On/Off"
    trigger:
    - platform: state
      entity_id: sensor.hal_motion
      to: 'True'
    - platform: state
      entity_id: sensor.hal_motion
      to: 'False'
      for:
        minutes: 5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.automation_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.light_automation_override
          state: 'off'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('sensor.switch_hal_lux', 'on') and is_state('sensor.hal_motion', 'True')-%}
            script.hal_en_overlopen
          {%- else -%}
            script.hal_en_overlopen_off
          {%- endif -%}

  # KIDS NACHTLAMP
  - alias: 'Lights Lex On/Off'
    trigger:
    - platform: time_pattern
      minutes: '/30'
      seconds: 00      
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.automation_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
    action:
    - service_template: >-
        {%- if not is_state('sensor.time_of_day_short', 'daytime') -%}
          homeassistant.turn_on
        {%- elif is_state('sensor.time_of_day_short', 'daytime') -%}
          homeassistant.turn_off
        {%- endif -%}
      entity_id: group.kinderen


################################################
## Group
################################################
group:
  buiten:
    - light.buiten
    - group.buiten_switches
  buiten_switches:
    - switch.tuin
  beneden:
    - light.woonkamer
    - light.keuken
  kinderen:
    # - switch.lex
    - light.slaapkamer_lex
    - switch.boris
  hal_en_overlopen:
    - light.hal_en_overlopen

################################################
## Script
################################################
script:

  lights_dummy:
    sequence:
    - service: homeassistant.turn_on
      entity_id: input_boolean.lights_dummy

 # ALL
  all_on:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_general
    - service: scene.turn_on
      entity_id: scene.keuken_general
    - service: scene.turn_on
      entity_id: scene.buiten_general
    - service: homeassistant.turn_on
      entity_id: group.buiten_switches
    - service: homeassistant.turn_on
      entity_id: switch.tv_woonkamer_verlichting

  all_on_bright:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_bright
    - service: scene.turn_on
      entity_id: scene.keuken_bright
    - service: scene.turn_on
      entity_id: scene.hal_en_overlopen_bright

  all_on_super_bright:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_super_bright
    - service: scene.turn_on
      entity_id: scene.keuken_super_bright
    - service: scene.turn_on
      entity_id: scene.hal_en_overlopen_super_bright

  all_off:
    sequence:
    - service: scene.turn_on
      entity_id: scene.all_off
    - service: homeassistant.turn_off
      entity_id: group.buiten_switches
    - service: homeassistant.turn_off
      entity_id: switch.tv_woonkamer_verlichting

# WOONKAMER
  woonkamer:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.woonkamer_
          {%- if states('sensor.time_of_day_short') in ['daytime'] -%}bright
          {%- else -%}general
          {%- endif -%}
    - service: homeassistant.turn_on
      entity_id: switch.tv_woonkamer_verlichting

  woonkamer_off:
    sequence:
    - service: light.turn_off
      entity_id: light.woonkamer
    - service: homeassistant.turn_off
      entity_id: light.buiten, group.buiten_switches, switch.tv_woonkamer_verlichting

# KEUKEN
  keuken:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.keuken_
          {%- if states('sensor.time_of_day_short') in ['daytime'] -%}bright
          {%- else -%}general
          {%- endif -%}

  keuken_off:
    sequence:
    - service: light.turn_off
      entity_id: light.keuken

# HAL EN OVERLOPEN
  hal_en_overlopen:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.hal_en_overlopen_
          {%- if states('sensor.time_of_day_short') in ['evening'] -%}evening
          {%- elif states('sensor.time_of_day_short') in ['night'] -%}night
          {%- else -%}general
          {%- endif -%}

  hal_en_overlopen_off:
    sequence:
    - service: light.turn_off
      entity_id: light.hal_en_overlopen

# BUITEN
  buiten:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.buiten_
          {%- if states('sensor.time_of_day_short') in ['evening'] -%}evening
          {%- elif states('sensor.time_of_day_short') in ['night'] -%}night
          {%- else -%}general
          {%- endif -%}
    - service_template: >-
        {%- if states('sensor.time_of_day_short') in ['early evening','evening'] -%}homeassistant.turn_on
        {%- else -%}homeassistant.turn_off
        {%- endif -%}
      entity_id: group.buiten_switches

  buiten_off:
    sequence:
    - service: homeassistant.turn_off
      entity_id: light.buiten, group.buiten_switches
