################################################
## Packages / Lights
################################################
homeassistant:
  customize:
    group.all_lights:
      control: hidden
    script.all_off:
      friendly_name: All Lights Off
      icon: mdi:flash
    script.woonkamer_off:
      friendly_name: Woonkamer
      icon: mdi:flashlight-off
    script.keuken_off:
      friendly_name: Keuken
      icon: mdi:flashlight-off
    script.hal_en_overlopen_off:
      friendly_name: Hal en Overlopen
      icon: mdi:flashlight-off
    script.buiten_off:
      friendly_name: Buiten
      icon: mdi:flashlight-off
    switch.all_on:
      friendly_name: All lights
      icon: mdi:flash
    script.all_on:
      friendly_name: All Lights On
      icon: mdi:flash
    script.all_on_bright:
      friendly_name: All Lights Bright
      icon: mdi:flash
    script.all_on_super_bright:
      friendly_name: All Lights Super Bright
      icon: mdi:flash
    script.woonkamer:
      friendly_name: Woonkamer
      icon: mdi:flashlight
    script.woonkamer_nightlight:
      friendly_name: Woonkamer NL
      icon: mdi:flashlight
    script.woonkamer_bright:
      friendly_name: Woonkamer B
      icon: mdi:flashlight
    script.woonkamer_super_bright:
      friendly_name: Woonkamer SB
      icon: mdi:flashlight
    script.keuken:
      friendly_name: Keuken
      icon: mdi:flashlight
    script.keuken_bright:
      friendly_name: Keuken B
      icon: mdi:flashlight
    script.keuken_super_bright:
      friendly_name: Keuken SB
      icon: mdi:flashlight
    script.hal_en_overlopen:
      friendly_name: Hal & Overlopen
      icon: mdi:flashlight
    script.hal_en_overlopen_nightlight:
      friendly_name: Hal & Overlopen NL
      icon: mdi:flashlight
    script.hal_en_overlopen_bright:
      friendly_name: Hal & Overlopen B
      icon: mdi:flashlight
    script.hal_en_overlopen_super_bright:
      friendly_name: Hal & Overlopen SB
      icon: mdi:flashlight
    script.buiten:
      friendly_name: Buiten
      icon: mdi:flashlight
    script.buiten_bright:
      friendly_name: Buiten B
      icon: mdi:flashlight
    script.buiten_super_bright:
      friendly_name: Buiten SB
      icon: mdi:flashlight
    sensor.woonkamer_motion:
      friendly_name: Woonkamer Motion
      icon: mdi:run-fast
    sensor.woonkamer_lux:
      friendly_name: Woonkamer Lux
      icon: mdi:theme-light-dark
    sensor.woonkamer_battery:
      friendly_name: Woonkamer Battery
      icon: mdi:battery
    sensor.hal_motion:
      friendly_name: Hal Motion
      icon: mdi:run-fast
    sensor.hal_lux:
      friendly_name: Hal Lux
      icon: mdi:theme-light-dark
    sensor.hal_battery:
      friendly_name: Hal Battery
      icon: mdi:battery
    sensor.switch_hal:
      friendly_name: Switch Hal
    sensor.switch_woonkamer:
      friendly_name: Switch Woonkamer
    sensor.hue_remote_1_state:
      friendly_name: Remote 1 State
      icon: mdi:remote
      persistence: false
    sensor.hue_remote_1_last_update:
      friendly_name: Remote 1 Last Update
      icon: mdi:clock
    sensor.hue_remote_1_battery:
      friendly_name: Remote 1 Battery
      icon: mdi:battery
    sensor.hue_remote_2_state:
      friendly_name: Remote 2 State
      icon: mdi:remote
      persistence: false
    sensor.hue_remote_2_last_update:
      friendly_name: Remote 2 Last Update
      icon: mdi:clock
    sensor.hue_remote_2_battery:
      friendly_name: Remote 2 Battery
      icon: mdi:battery
    input_number.keuken_hanglamp_brightness:
      friendly_name: Keuken Hanglamp

################################################
## Hue
################################################
hue:
  bridges:
    - host: !secret philips_hue_host
      allow_unreachable: true
      allow_hue_groups: true

################################################
## Input Number
################################################
input_number:
  keuken_hanglamp_brightness:
    initial: 127
    min: 0
    max: 255
    step: 1

input_boolean:
  automation_mode:
    name: "Automation Mode"
    initial: off
    icon: mdi:human-male-female
  vacation_mode:
    name: "Vacation Mode"
    initial: off
    icon: mdi:human-male-female
  woonkamer_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female
  hal_motion:
    name: "Woonkamer Motion"
    initial: off
    icon: mdi:human-male-female

################################################
## Sensor
################################################
sensor:
  - platform: rest
    resource: !secret hue_woonkamer_battery_sensor
    value_template: '{{ value_json.config.battery }}'
    scan_interval: 1800
    unit_of_measurement: '%'
    name: 'woonkamer_battery'
  - platform: rest
    resource: !secret hue_woonkamer_motion_sensor
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: 'woonkamer_motion'
  - platform: rest
    resource: !secret hue_woonkamer_lux_sensor
  #  value_template: '{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}}'
    value_template: '{{ value_json.state.lightlevel }}'
    scan_interval: 30
    unit_of_measurement: 'Lux'
    name: 'woonkamer_lux'

  # Philips HUE - Sensors - Hal en Overlopen
  - platform: rest
    resource: !secret hue_hal_battery_sensor
    value_template: '{{ value_json.config.battery }}'
    scan_interval: 1800
    unit_of_measurement: '%'
    name: 'hal_battery'
  - platform: rest
    resource: !secret hue_hal_motion_sensor
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: 'hal_motion'
  - platform: rest
    resource: !secret hue_hal_lux_sensor
    value_template: '{{ value_json.state.lightlevel }}'
    scan_interval: 30
    unit_of_measurement: 'Lux'
    name: 'hal_lux'

  # Philips HUE - Remote 1
  - platform: rest
    resource: !secret hue_remote_1
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'hue_remote_1_battery'
  - platform: rest
    resource: !secret hue_remote_1
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 1
    name: 'hue_remote_1_state'
  - platform: template
    sensors:
      hue_remote_1_state:
        friendly_name: 'hue_remote_1_state'
        value_template: >-
          {%- if states('sensor.hue_remote_1_state_2')[0] == "1" -%} On
          {%- elif states('sensor.hue_remote_1_state_2')[0] == "2" -%} Dim Up
          {%- elif states('sensor.hue_remote_1_state_2')[0] == "3" -%} Dim Down
          {%- elif states('sensor.hue_remote_1_state_2')[0] == "4" -%} Off
          {%- else -%} None
          {%- endif -%}
  - platform: rest
    resource: !secret hue_remote_1
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'hue_remote_1_last_update'
  - platform: template
    sensors:
      hue_remote_1_last_update:
        friendly_name: 'hue_remote_1_last_used'
        value_template: >-
          {{ as_timestamp(strptime(states('sensor.hue_remote_1_last_update_2')[:19], "%Y-%m-%dT%X"))|timestamp_custom("%a, %B %d")}}

  # Philips HUE - Remote 2
  - platform: rest
    resource: !secret hue_remote_2
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'hue_remote_2_battery'
  - platform: rest
    resource: !secret hue_remote_2
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 1
    name: 'hue_remote_2_state'
  - platform: template
    sensors:
      hue_remote_2_state:
        friendly_name: 'hue_remote_2_state'
        value_template: >-
          {%- if states('sensor.hue_remote_2_state_2')[0] == "1" -%} On
          {%- elif states('sensor.hue_remote_2_state_2')[0] == "2" -%} Dim Up
          {%- elif states('sensor.hue_remote_2_state_2')[0] == "3" -%} Dim Down
          {%- elif states('sensor.hue_remote_2_state_2')[0] == "4" -%} Off
          {%- else -%} None
          {%- endif -%}
  - platform: rest
    resource: !secret hue_remote_2
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'hue_remote_2_last_update'
  - platform: template
    sensors:
      hue_remote_2_last_update:
        friendly_name: 'hue_remote_2_last_used'
        value_template: >-
          {{ as_timestamp(strptime(states('sensor.hue_remote_2_last_update_2')[:19], "%Y-%m-%dT%X"))|timestamp_custom("%a, %B %d")}}

  - platform: template
    sensors:
      keuken_hanglamp_brightness:
        value_template: >-
          {%- if is_state('light.keuken_hanglamp', 'on') -%}
            {{ states.light.keuken_hanglamp.attributes.brightness | int }}
          {%- else -%}
            127
          {%- endif -%}
      switch_hal:
        value_template: >-
          {%- if states('sensor.hal_lux') | int < 6000 -%} on
          {%- else -%} off
          {%- endif -%}
      switch_woonkamer:
        value_template: >-
          {%- if states('sensor.woonkamer_lux') | int < 12000 -%} on
          {%- else -%} off
          {%- endif -%}

################################################
## Automation
################################################
automation:

  # KEUKEN
  - alias: "Slider - Keuken - Hanglamp - Set value"
    initial_state: on
    trigger:
    - platform: state
      entity_id: sensor.keuken_hanglamp_brightness
    - platform: state
      entity_id: light.keuken_hanglamp
      from: 'off'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.keuken_hanglamp_brightness
        value: "{{ states.light.keuken_hanglamp.attributes.brightness | int }}"

  - alias: "Switch - Keuken - Hanglamp - On"
    trigger:
    - platform: state
      entity_id: input_number.keuken_hanglamp_brightness
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.keuken_hanglamp
        brightness: "{{ trigger.to_state.state | int }}"

  # FRONTDOOR
  - alias: "Motion and Person - Doorbel - Turn On/Off"
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_person_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_motion_detected
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.front_door_camera_voordeur_person_detected
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      before: '05:00:00'
      after: '00:00:00'
    action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('binary_sensor.front_door_camera_voordeur_motion_detected', 'on') or is_state('binary_sensor.front_door_camera_voordeur_motion_detected', 'on') -%}
          scene.buiten_bright
          {%- else -%}
          script.off
          {%- endif -%}

  # GENERAL
  - alias: "General lights On/Off"
    trigger:
    - platform: time
      minutes: '/10'
      seconds: 00
    - platform: state
      entity_id: sensor.switch_woonkamer
      from: 'off'
      to: 'on'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.switch_woonkamer
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: sensor.hal_motion
      to: 'True'
    - platform: state
      entity_id: sensor.woonkamer_motion
      to: 'True'
    condition:
    - condition: state
      entity_id: input_boolean.automation_mode
      state: 'off'
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if (is_state('sensor.switch_woonkamer', 'on') and is_state('sensor.switch_hal', 'on')) and states('sensor.time_of_day_short') in ['daytime','early evening'] -%}
          script.woonkamer, script.keuken, script.buiten
          {%- elif (is_state('sensor.woonkamer_motion', 'True') or is_state('sensor.hal_motion', 'True')) and states('sensor.time_of_day_short') in ['night'] -%}
          script.woonkamer, script.keuken
          {%- elif is_state('media_player.livingroom_tv', 'off') and states('sensor.time_of_day_short') in ['evening','night'] -%}
          script.all_off
          {%- elif is_state('sensor.switch_woonkamer', 'off') and states('sensor.time_of_day_short') in ['daytime','early evening'] -%}
          script.all_off
          {%- endif -%}

  # HAL & OVERLOPEN
  - alias: "Hal en overlopen On/Off"
    trigger:
    - platform: state
      entity_id: sensor.hal_motion
      to: 'True'
    - platform: state
      entity_id: sensor.hal_motion
      to: 'False'
      for:
        minutes: 10
    action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if is_state('sensor.switch_hal', 'on') and is_state('sensor.hal_motion', 'True')-%}
          script.hal_en_overlopen
          {%- else -%}
          script.hal_en_overlopen_off
          {%- endif -%}

# KIDS NACHTLAMP
  - alias: 'Lights Lex On/Off'
    trigger:
    - platform: sun
      event: sunset
      offset: "-00:15:00"
    - platform: sun
      event: sunrise
      offset: '+00:00:00'
    action:
    - service_template: >-
        {%- if trigger.event == "sunset" -%}
        homeassistant.turn_on
        {%- elif trigger.event == "sunrise" -%}
        homeassistant.turn_off
        {%- endif -%}
      entity_id: group.kinderen

################################################
## Group
################################################
group:
  buiten:
    - light.buitenachter
    - light.buitenvoor
    - switch.smartplug2
  beneden:
    - light.woonkamer
    - light.keuken
  kinderen:
    - switch.smartplug4
    - switch.smartplug7
  hal_en_overlopen:
    - light.hal_en_overlopen

################################################
## Script
################################################
script:
# ALL
  all_on:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_general
    - service: scene.turn_on
      entity_id: scene.keuken_general

  all_on_bright:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_bright
    - service: scene.turn_on
      entity_id: scene.keuken_bright
    - service: scene.turn_on
      entity_id: scene.hal_en_overlopen_bright

  all_on_super_bright:
    sequence:
    - service: scene.turn_on
      entity_id: scene.woonkamer_super_bright
    - service: scene.turn_on
      entity_id: scene.keuken_super_bright
    - service: scene.turn_on
      entity_id: scene.hal_en_overlopen_super_bright

  all_off:
    sequence:
    - service: scene.turn_on
      entity_id: scene.all_off

# WOONKAMER
  woonkamer:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.woonkamer_
          {%- if states('sensor.time_of_day_short') in ['daytime'] -%}bright
          {%- else -%}general
          {%- endif -%}

  woonkamer_off:
    sequence:
    - service: light.turn_off
      entity_id: light.woonkamer

# KEUKEN
  keuken:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.keuken_
          {%- if states('sensor.time_of_day_short') in ['daytime'] -%}bright
          {%- else -%}general
          {%- endif -%}

  keuken_off:
    sequence:
    - service: light.turn_off
      entity_id: light.keuken

# HAL EN OVERLOPEN
  hal_en_overlopen:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          scene.hal_en_overlopen_
          {%- if states('sensor.time_of_day_short') in ['evening','night'] -%}night
          {%- else -%}general
          {%- endif -%}

  hal_en_overlopen_off:
    sequence:
    - service: light.turn_off
      entity_id: light.hal_en_overlopen

# BUITEN
  buiten:
    sequence:
    - service: scene.turn_on
      data_template:
        entity_id: scene.buiten_general

  buiten_off:
    sequence:
    - service: light.turn_off
      entity_id: group.buiten