################################################
## Packages / Device tracker
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    device_tracker.taipan5g:
      friendly_name: Bram
    device_tracker.lieke_iphone:
      friendly_name: Lieke
    zone.home:
      friendly_name: "Home"
    zone.work_lieke:
      friendly_name: "Work"
      icon: mdi:briefcase
    zone.parents_lieke:
      friendly_name: "Parents"
      icon: mdi:cow
    zone.zus_lieke:
      friendly_name: "Zus"
      icon: mdi:cow
    sensor.bram_distance_to_home:
      friendly_name: Bram - Distance to home
      icon: mdi:car
    sensor.lieke_distance_to_home:
      friendly_name: Lieke - Distance to home
      icon: mdi:car

################################################
## Device Tracker
################################################
device_tracker:
  - platform: unifi_direct
    host: !secret ap_host
    username: !secret ap_username
    password: !secret ap_password

  - platform: nmap_tracker
    hosts:
      - !secret nmap_hosts

  - platform: luci
    host: !secret openwrt_tracker_boven_host
    username: !secret openwrt_tracker_boven_username
    password: !secret openwrt_tracker_boven_password

################################################
## Zone
################################################
zone:
  - name: work lieke
    latitude: !secret lieke_work_latitude
    longitude: !secret lieke_work_longtitude
    radius: 250

  - name: parents lieke
    latitude: !secret lieke_parents_home_latitude
    longitude: !secret lieke_parents_home_longtitude
    radius: 150

  - name: zus lieke
    latitude: !secret lieke_daan_en_jels_latitude
    longitude: !secret lieke_daan_en_jels_longtitude
    radius: 150

################################################
## Sensor
################################################
sensor:
  - platform: google_travel_time
    name: Bram Distance To Home
    api_key: !secret google_travel_time_key_bram
    origin: device_tracker.taipan5g
    destination: zone.home

  - platform: google_travel_time
    name: Lieke Distance To Home
    api_key: !secret google_travel_time_key_lieke
    origin: device_tracker.lieke_iphone
    destination: zone.home

  - platform: google_travel_time
    name: Lieke Distance To Home
    api_key: !secret google_travel_time_key_lieke
    origin: zone.work_lieke
    destination: zone.home

################################################
## Automation
################################################
automation:
  - alias: Alert zone change - Enter
    trigger:
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.work_lieke
      event: enter
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.parents_lieke
      event: enter
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.zus_lieke
      event: enter
    action:
    - service: notify.bram
      data_template:
        message: '{{ trigger.to_state.attributes.friendly_name }} entered {{ trigger.zone.attributes.friendly_name }} at {{ states("sensor.time") }}!'

  - alias: Alert zone change - Leave
    trigger:
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.home
      event: leave
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.work_lieke
      event: leave
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.parents_lieke
      event: leave
    - platform: zone
      entity_id: device_tracker.lieke_iphone
      zone: zone.zus_lieke
      event: leave
    action:
    - service: notify.bram
      data_template:
        message: '{{ trigger.to_state.attributes.friendly_name }} left {{ trigger.zone.attributes.friendly_name }} at {{ states("sensor.time") }}!'

  - alias: Lieke is 10 minutes from home
    trigger:
    - platform: numeric_state
      entity_id: sensor.lieke_distance_to_home
      value_template: '{{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] | int *60 }}'
      below: 600
    condition:
    - condition: state
      entity_id: 'device_tracker.lieke_iphone'
      state: 'not_home'
    action:
    - service: notify.bram
      data:
        message: 'Lieke is {{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] }} minutes from home'
        data:
          push:
            category: map
          action_data:
            shows_user_location: true
            latitude: "{{ trigger.to_state.attributes.latitude }}"
            longitude: "{{ trigger.to_state.attributes.longitude }}"


#        value_template: >-
#          {%- if is_state('states.sensor.lieke_distance_to_home', 'unknown') -%}
#            0
#          {%- else -%}
#            {{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] | int *60 }}
#          {%- endif -%}