################################################
## Packages / Device tracker
################################################
homeassistant:
  customize:
    device_tracker.taipan5g:
      friendly_name: Bram
      entity_picture: /local/faces/bram.jpg
    device_tracker.lieke_iphone:
      friendly_name: Lieke
      entity_picture: /local/faces/lieke.jpg
    zone.home:
      friendly_name: "Home"
    zone.work_lieke:
      friendly_name: "Work"
      icon: mdi:briefcase
    zone.parents_lieke:
      friendly_name: "Parents"
      icon: mdi:cow
    zone.zus_lieke:
      friendly_name: "Zus"
      icon: mdi:cow
    sensor.bram_distance_to_home:
      friendly_name: Bram - Distance to home
      icon: mdi:car
    sensor.lieke_distance_to_home:
      friendly_name: Lieke - Distance to home
      icon: mdi:car

################################################
## Device Tracker
################################################
device_tracker:
  - platform: unifi
    host: !secret nas_host_ip
    port: !secret unifi_port
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    interval_seconds: 120
    consider_home: 120
    detection_time: 60
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

  # - platform: unifi_direct
  #   host: !secret ap1_host
  #   username: !secret ap_username
  #   password: !secret ap_password
  #   interval_seconds: 120
  #   consider_home: 240
  #   new_device_defaults:
  #     track_new_devices: true
  #     hide_if_away: false

  # - platform: unifi_direct
  #   host: !secret ap2_host
  #   username: !secret ap_username
  #   password: !secret ap_password
  #   interval_seconds: 120
  #   consider_home: 240
  #   new_device_defaults:
  #     track_new_devices: true
  #     hide_if_away: false

  - platform: google_maps
    username: liekesmidspad@gmail.com
    max_gps_accuracy: 200

  - platform: nmap_tracker
    home_interval: 120
    hosts:
      - !secret nmap_hosts

################################################
## Zone
################################################
zone:
  - name: work lieke
    latitude: !secret lieke_work_latitude
    longitude: !secret lieke_work_longtitude
    radius: 100

  - name: sport lieke
    latitude: !secret lieke_sport_latitude
    longitude: !secret lieke_sport_longtitude
    radius: 100

  - name: parents lieke
    latitude: !secret lieke_parents_home_latitude
    longitude: !secret lieke_parents_home_longtitude
    radius: 100

  - name: zus lieke
    latitude: !secret lieke_daan_en_jels_latitude
    longitude: !secret lieke_daan_en_jels_longtitude
    radius: 100

################################################
## Sensor
################################################
sensor:
  - platform: google_travel_time
    name: Bram Distance To Home
    api_key: !secret google_travel_time_key_bram
    origin: device_tracker.taipan5g
    destination: zone.home

  - platform: google_travel_time
    name: Lieke Distance To Home
    api_key: !secret google_travel_time_key_lieke
    origin: device_tracker.lieke_iphone
    destination: zone.home

################################################
## Automation
################################################
automation:
#  - alias: Alert zone change - Enter
  #   trigger:
  #   - platform: zone
  #     event: enter
  #     zone: zone.home
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: enter
  #     zone: zone.work_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: enter
  #     zone: zone.sport_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: enter
  #     zone: zone.parents_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: enter
  #     zone: zone.zus_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   action:
  #   - service: notify.bram
  #     data_template:
  #       message: '{{ trigger.to_state.attributes.friendly_name }} entered {{ trigger.zone.attributes.friendly_name }} at {{ states("sensor.time") }}!'
  #       data:
  #         push:
  #           category: map
  #         action_data:
  #           shows_user_location: true
  #           latitude: "{{ trigger.to_state.attributes.latitude }}"
  #           longitude: "{{ trigger.to_state.attributes.longitude }}"

  # - alias: Alert zone change - Leave
  #   trigger:
  #   - platform: zone
  #     event: leave
  #     zone: zone.home
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: leave
  #     zone: zone.work_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: leave
  #     zone: zone.sport_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: leave
  #     zone: zone.parents_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   - platform: zone
  #     event: leave
  #     zone: zone.zus_lieke
  #     entity_id: device_tracker.lieke_iphone
  #   action:
  #   - service: notify.bram
  #     data_template:
  #       message: '{{ trigger.to_state.attributes.friendly_name }} left {{ trigger.zone.attributes.friendly_name }} at {{ states("sensor.time") }}!'
  #       data:
  #         push:
  #           category: map
  #         action_data:
  #           shows_user_location: true
  #           latitude: "{{ trigger.to_state.attributes.latitude }}"
  #           longitude: "{{ trigger.to_state.attributes.longitude }}"

  # - alias: Lieke is 10 minutes from home
  #   trigger:
  #   - platform: numeric_state
  #     entity_id: sensor.lieke_distance_to_home
  #     value_template: '{{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] | int *60 }}'
  #     below: 600
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: template
  #         value_template: "{{ states('device_tracker.lieke_iphone') != 'home' }}"
  #   action:
  #   - service: notify.bram
  #     data_template:
  #       message: 'Lieke is {{ states.sensor.lieke_distance_to_home.attributes.duration.split(" ")[0] }} minutes from home'

  - alias: "Commute - Update sensor"
    initial_state: 'on'
    trigger:
    - platform: time_pattern
      minutes: '/2'
      seconds: 00
    action:
    - service: homeassistant.update_entity
      entity_id: sensor.lieke_distance_to_home


  # - alias: LocateAidan
  #   trigger:
  #     platform: state
  #     entity_id: device_tracker.lieke_iphone
  #   action:
  #     service: notify.ios_my_iphone
  #     data_template:
  #       title: Location Alert
  #       message: >
  #         Aidan: '{{ states("sensor.time") }} Location has changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
  #       data:
  #         attachment:
  #           content-type: jpeg
  #         push:
  #           category: camera
  #         entity_id: camera.location_aidan
      # service: notify.ios_<your_device_id_here>
      # data:
      #   message: Motion detected in the Living Room
      #   data:
      #     attachment:
      #       content-type: jpeg
      #     push:
      #       category: camera
      #     entity_id: camera.demo_camera
