################################################
## Packages / Logger
################################################
homeassistant:

################################################
## Logger
################################################
logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    urllib3.connectionpool: critical

# system_log:
#   max_entries: 0

################################################
## Input Select
################################################
input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn

################################################
## Automation
################################################
automation:
  - alias: Log Level
    trigger:
      platform: state
      entity_id:
        - input_select.log_level
    action:
      - service: logger.set_level
        data_template:
          homeassistant.components: "{{ states.input_select.log_level.state }}"
      - service: notify.bram
        data_template:
          message: "Home Assistant logging level has been set to {{ states.input_select.log_level.state }}"
