################################################
## Packages / Logger
################################################
homeassistant:

################################################
## Logger
################################################
logger:
  default: info
  logs:
    # aiounifi: debug
    # homeassistant.components.unifi: debug
    # homeassistant.components.device_tracker.unifi: debug
    # homeassistant.components.switch.unifi: debug
    requests.packages.urllib3.connectionpool: critical
    urllib3.connectionpool: critical
    py.warnings: critical
    # homeassistant.components.device_tracker: critical
    # homeassistant.components.automation: debug
    # homeassistant.components.light: info
    # homeassistant.components.sensor: info
    # homeassistant.components.switch: info
    # homeassistant.components.device_tracker.unifi: critical
    # homeassistant.components.device_tracker.unifi_direct: critical
    # custom_components.sensor.mijnafvalwijzer: debug

# system_log:
#   max_entries: 0

################################################
## Inputs
################################################
input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: info

################################################
## Automation
################################################
automation:
  - alias: Log Level
    trigger:
      platform: state
      entity_id:
        - input_select.log_level
    action:
      - service: logger.set_level
        data_template:
          homeassistant.components: "{{ states.input_select.log_level.state }}"
      - service: notify.bram
        data_template:
          message: "Home Assistant logging level has been set to {{ states.input_select.log_level.state }}"
