################################################
## Packages / Plex
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    media_player.livingroom_tv:
      friendly_name: "Livingroom TV"
    media_player.bedroom_tv:
      friendly_name: "Bedroom TV"
    sensor.plex_activity:
      friendly_name: "Plex Activity"

################################################
## Input Boolean
################################################
input_boolean:
  tv_status_woonkamer:
    name: "TV Status - Woonkamer"
    initial: off

################################################
## Media Player
################################################
media_player:
  - platform: webostv
    host: !secret lgwebostv_host_1
    name: Livingroom TV
    customize:
      sources:
        - livetv
        - plex
        - xplay
        - youtube
        - netflix
    filename: webostv1.conf

  - platform: webostv
    host: !secret lgwebostv_host_2
    name: Bedroom TV
    customize:
      sources:
        - livetv
        - plex
        - xplay
        - youtube
        - netflix
    filename: webostv2.conf

################################################
## Sensor
################################################
sensor:
  - platform: plex
    name: plex_activity
    host: !secret plex_host
    port: !secret plex_port
    username: !secret plex_username
    password: !secret plex_password
    token: !secret plex_token

  - platform: history_stats
    name: TV livingroom on last 30 days
    entity_id: media_player.livingroom_tv
    state: 'on'
    type: time
    end: '{{ now() }}'
    duration:
      days: 30

  - platform: history_stats
    name: TV bedroom on last 30 days
    entity_id: media_player.bedroom_tv
    state: 'on'
    type: time
    end: '{{ now() }}'
    duration:
      days: 30

################################################
## Automation
################################################
automation:
  - alias: "Woonkamer TV - Off"
    trigger:
    - platform: state
      entity_id: media_player.livingroom_tv
      to: "off"
    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.tv_status_woonkamer

  - alias: "Woonkamer TV - On"
    trigger:
    - platform: state
      entity_id: media_player.livingroom_tv
      to: "playing"
    action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.tv_status_woonkamer
