################################################
## Packages / Plex
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'media_players'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    media_player.livingroom_tv:
      <<: *customize
      friendly_name: "Livingroom TV"
    media_player.bedroom_tv:
      <<: *customize
      friendly_name: "Bedroom TV"
    sensor.plex_activity:
      <<: *customize
      friendly_name: "Plex Activity"

################################################
## Media Player
################################################
media_player:
  - platform: webostv
    host: !secret lgwebostv_host_1
    name: Livingroom TV
    customize:
      sources:
        - livetv
        - plex
        - xplay
        - youtube
        - netflix
    filename: webostv1.conf
  - platform: webostv
    host: !secret lgwebostv_host_2
    name: Bedroom TV
    customize:
      sources:
        - livetv
        - plex
        - xplay
        - youtube
        - netflix
    filename: webostv2.conf

################################################
## Sensor
################################################
sensor:
  - platform: plex
    name: plex_activity
    host: !secret plex_host
    port: !secret plex_port
    username: !secret plex_username
    password: !secret plex_password
    token: !secret plex_token

################################################
## Automation
################################################
automation:
  - alias: "Woonkamer TV - Off"
    trigger:
    - platform: state
      entity_id: media_player.livingroom_tv
      to: "off"
    action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.tv_status_woonkamer

  - alias: "Woonkamer TV - On"
    trigger:
    - platform: state
      entity_id: media_player.livingroom_tv
      to: "playing"
    action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.tv_status_woonkamer
