################################################
## Packages / Medicines
################################################
homeassistant:

################################################
## Input Boolean
################################################
input_boolean:
  meds_taken:
    name: Bram Medicijnen Ingenomen
    initial: 'off'
    icon: mdi:pill
  meds_reminder:
    name: Bram Medicijnen Reminder
    initial: 'on'

################################################
## Automation
################################################
automation:
  - alias: Reset meds taken
    trigger:
      platform: state
      entity_id: input_boolean.meds_taken
      to: 'on'
      for:
        hours: 8
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.meds_taken
      - service: input_boolean.turn_on
        entity_id: input_boolean.meds_reminder        

  - alias: Mark meds as taken from notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_MEDS_TAKEN
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.meds_taken

  - alias: Meds have not been taken
    trigger:
      platform: time_pattern
      minutes: '/30'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: state
          entity_id: input_boolean.meds_reminder
          state: 'on'
        - condition: time
          after: '8:00:00'
          before: '12:00:00'
    action:
      - service: notify.bram
        data:
          title: "Medicijnen"
          message: "Medicijnen innemen!"
          data:
            push:
              badge: 0
              category: 'medicijnen'
