################################################
## Packages / Notify
################################################

################################################
## Customize
################################################
homeassistant:
  customize:

################################################
## Component
################################################
ios:
  push:
    categories:
      - name: Medicijnen
        identifier: 'medicijnen'
        actions:
          - identifier: 'MARK_MEDS_TAKEN'
            title: 'Medicijnen ingenomen'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: Afval
        identifier: 'afval'
        actions:
          - identifier: 'MARK_TRASH_MOVED'
            title: 'Afval verwerkt'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

################################################
## Notify
################################################
notify:
  - platform: group
    name: family
    services:
      - service: ios_taipan5g
      - service: ios_lieke_iphone
  - platform: group
    name: bram
    services:
      - service: ios_taipan5g
