################################################
## Packages / Notify
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'notify'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

################################################
## Notify
################################################
notify:
  - platform: group
    name: family
    services:
      - service: ios_taipan5g
      - service: ios_lieke_iphone
  - platform: group
    name: bram
    services:
      - service: ios_taipan5g
      - service: ios_lieke_iphone