################################################
## Packages / pi-hole
################################################
homeassistant:
  customize:
    sensor.pihole_status:
       friendly_name: Pi-Hole Status

################################################
## Input Select
################################################
input_select:
  pihole_time:
    name: Disable Time (seconds)
    options:
      - Select Time
      - 10
      - 30
      - 60
      - 300
      - 600
      - 900
      - 1800
      - 3600
    initial: Select Time

################################################
## Sensor
################################################
sensor:
  - platform: pi_hole
    host: !secret pi_hole_host
    ssl: false
    verify_ssl: false
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
      - clients_ever_seen

  - platform: command_line
    command: !secret pi_hole_status
    name: 'pihole_status'
    value_template: '{{ value_json.status }}'
    scan_interval: 10

################################################
## Script
################################################
script:
  enable_pihole:
    alias: Pi-Hole Enable
    sequence:
      service: shell_command.pihole_enable

################################################
## Shell Command
################################################
shell_command:
  pihole_enable: !secret pi_hole_switch_on
  pihole_disable: !secret pi_hole_switch_off

################################################
## Automation
################################################
automation:
  - alias: Disable Pi-Hole
    trigger:
      platform: state
      entity_id: input_select.pihole_time
    action:
      service: shell_command.pihole_disable

  - alias: Reset PiHole Disable Time
    trigger:
      - platform: state
        entity_id: script.enable_pihole
      - platform: state
        entity_id: sensor.pihole_status
        from: 'disabled'
        to: 'enabled'
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.pihole_time
        option: Select Time
