################################################
## Packages / Power Plugs
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'power_plugs'
      expose: &expose # This merges the keys/values from "&customize"
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    switch.smartplug1:
      <<: *customize
      hidden: false
      friendly_name: Wasmachine
    switch.smartplug2:
      <<: *customize
      hidden: false
      friendly_name: Tuinverlichting
    switch.smartplug3:
      <<: *customize
      hidden: false
      friendly_name: Droger

################################################
## Switch
################################################
switch:
  - platform: tplink
    host: 192.168.1.157
  - platform: tplink
    host: 192.168.1.182
  - platform: tplink
    host: 192.168.1.183

group:
  hometracking:
    name: Household Tracking
    view: no
    entities:
      - device_tracker.taipan5g
      - device_tracker.lieke_iphone

################################################
## Inputs
################################################
input_boolean:
  wasmachine:
    name: Wasmachine status
    initial: off
    icon: mdi:washing-machine
  droger:
    name: Droger status
    initial: off
    icon: mdi:tumble-dryer

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      smartplug1_watts:
        friendly_name: "Huidig verbruik wasmachine"
        icon_template: mdi:washing-machine
        value_template: '{{ states.switch.smartplug1.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      smartplug1_kw_today:
        friendly_name: "Today's KiloWatts"
        value_template: '{{ states.switch.smartplug1.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      smartplug1_amps:
        friendly_name: "Amps"
        value_template: '{{ states.switch.smartplug1.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      smartplug1_kw:
        friendly_name: "Current KiloWatts"
        value_template: '{{ states.switch.smartplug1.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      smartplug1_volts:
        friendly_name: "Current Voltage"
        value_template: '{{ states.switch.smartplug1.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'

  - platform: template
    sensors:
      smartplug2_watts:
        friendly_name: "Huidig verbruik tuin"
        value_template: '{{ states.switch.smartplug2.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      smartplug2_kw:
        friendly_name: "Current KiloWatts"
        value_template: '{{ states.switch.smartplug2.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      smartplug2_amps:
        friendly_name: "Amps"
        value_template: '{{ states.switch.smartplug2.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      smartplug2_kw_today:
        friendly_name: "Today's KiloWatts"
        value_template: '{{ states.switch.smartplug2.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      smartplug2_volts:
        friendly_name: "Current Voltage"
        value_template: '{{ states.switch.smartplug2.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'

  - platform: template
    sensors:
      smartplug3_watts:
        friendly_name: "Huidig verbruik droger"
        icon_template: mdi:tumble-dryer
        value_template: '{{ states.switch.smartplug3.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      smartplug3_kw:
        friendly_name: "Current KiloWatts"
        value_template: '{{ states.switch.smartplug3.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      smartplug3_amps:
        friendly_name: "Amps"
        value_template: '{{ states.switch.smartplug3.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      smartplug3_kw_today:
        friendly_name: "Today's KiloWatts"
        value_template: '{{ states.switch.smartplug3.attributes["today_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kWh'
      smartplug3_volts:
        friendly_name: "Current Voltage"
        value_template: '{{ states.switch.smartplug3.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'

# WASMACHINE
  - platform: template
    sensors:
      wasmachine_status_time:
        friendly_name: "Wasmachine draaitijd"
        unit_of_measurement: 'minuten'
        icon_template: mdi:washing-machine
        value_template: >
          {% if is_state("input_boolean.wasmachine", "on") -%}
            {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }}
          {% else %}
            0
          {% endif %}
        entity_id: sensor.time
      wasmachine_status_value:
        friendly_name: "Wasmachine status"
        icon_template: mdi:washing-machine        
        value_template: >-
          {%- if is_state('input_boolean.wasmachine', 'on') -%}
            Aan
          {%- else -%}
            Uit
          {%- endif -%}
  - platform: statistics
    name: Wasmachine statistics
    entity_id: sensor.smartplug1_watts

# DROGER
  - platform: template
    sensors:
      droger_status_time:
        friendly_name: "Droger draaitijd"
        unit_of_measurement: 'minuten'
        icon_template: mdi:tumble-dryer
        value_template: >
          {% if is_state("input_boolean.droger", "on") -%}
            {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }}
          {% else %}
            0
          {% endif %}
        entity_id: sensor.time
      droger_status_value:
        friendly_name: "Droger status"
        icon_template: mdi:tumble-dryer
        value_template: >-
          {%- if is_state('input_boolean.droger', 'on') -%}
            Aan
          {%- else -%}
            Uit
          {%- endif -%}
  - platform: statistics
    name: Droger statistics
    entity_id: sensor.smartplug3_watts

################################################
## Automation
################################################
automation:

# WASMACHINE
  - alias: Action - Set wasmachine to running
    trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_statistics_mean
      above: 5
      for:
        minutes: 5
    condition: []
    action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.wasmachine
    - service: notify.family
      data_template:
        title: 'Wasmachine:'
        message: "Wasprogramma gestart."

  - alias: Action - Set wasmachine as finished
    trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_statistics_mean
      below: 5
      for:
        minutes: 5
    condition:
    - condition: state
      entity_id: input_boolean.wasmachine
      state: 'on'
    action:
    - service: notify.family
      data_template:
        title: 'Wasmachine:'
        message: "Wasprogramma gereed. Doorlooptijd: {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }} minuten."
    - service: homeassistant.turn_off
      entity_id: input_boolean.wasmachine

# DROGER
  - alias: Action - Set droger to running
    trigger:
    - platform: numeric_state
      entity_id: sensor.droger_statistics_mean
      above: 5
      for:
        minutes: 5
    condition: []
    action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.droger
    - service: notify.family
      data_template:
        title: 'Droger:'
        message: "Droger gestart."

  - alias: Action - Set droger as finished
    trigger:
    - platform: numeric_state
      entity_id: sensor.droger_statistics_mean
      below: 5
      for:
        minutes: 5
    condition:
    - condition: state
      entity_id: input_boolean.droger
      state: 'on'
    action:
    - service: notify.family
      data_template:
        title: 'Droger:'
        message: "Droger gereed. Doorlooptijd: {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }} minuten."
    - service: homeassistant.turn_off
      entity_id: input_boolean.droger