################################################
## Packages / Printers
################################################
homeassistant:

################################################
## Printer
################################################
sensor:
- platform: syncthru
  resource: !secret printer
  name: Samsung Printer
  monitored_conditions:
    - toner_black
    - tray_1
    - output_tray_0
