################################################
## Packages / Protection
################################################
homeassistant:
  customize:
    sensor.living_room_nest_protect_co_status:
      friendly_name: CO status - Woonkamer
    sensor.living_room_nest_protect_smoke_status:
      friendly_name: Smoke status - Woonkamer
      icon: mdi:fire
    sensor.living_room_nest_protect_battery_health:
      friendly_name: Battery status - Woonkamer
      icon: mdi:battery
    sensor.entryway_nest_protect_co_status:
      friendly_name: CO status - HAL
    sensor.entryway_nest_protect_smoke_status:
      friendly_name: Smoke status - HAL
      icon: mdi:fire
    sensor.entryway_nest_protect_battery_health:
      friendly_name: Battery status - HAL
      icon: mdi:battery
    sensor.hallway_nest_protect_co_status:
      friendly_name: CO status - Overloop
    sensor.hallway_nest_protect_smoke_status:
      friendly_name: Smoke status - Overloop
      icon: mdi:fire
    sensor.hallway_nest_protect_battery_health:
      friendly_name: Battery status - Overloop
      icon: mdi:battery

################################################
## Nest
################################################
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

################################################
## Automation
################################################
automation:
  - alias: 'Notify if Nest Protect is in an emergency state'
    trigger:
    - platform: state
      entity_id:
        - sensor.living_room_nest_protect_co_status
        - sensor.living_room_nest_protect_smoke_status
        - sensor.entryway_nest_protect_co_status
        - sensor.entryway_nest_protect_smoke_status
        - sensor.hallway_nest_protect_co_status
        - sensor.hallway_nest_protect_smoke_status
      to: 'Emergency'
    action:
    - service: notify.family
      data_template:
        title: 'Emergency'
        message: "An emergency has been detected on {{ trigger.to_state.attributes.friendly_name }}!"

  - alias: 'Notify if Nest Protect is offline'
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_nest_protect_online
        - binary_sensor.entryway_nest_protect_online
        - binary_sensor.hallway_nest_protect_online
      from: 'on'
    action:
    - service: notify.family
      data_template:
        title: 'Emergency'
        message: "The {{ trigger.to_state.attributes.friendly_name }} is now {{ (trigger.to_state.state)|replace('_', ' ') }}!"
