################################################
## Packages / Recorder
################################################
homeassistant:

################################################
## Recorder
################################################
recorder:
  purge_keep_days: 15
  purge_interval: 7
  #db_url: !secret recorder_db_url
