################################################
## Packages / Recorder
################################################
homeassistant:

################################################
## Recorder
################################################
recorder:
  purge_keep_days: 60
  purge_interval: 1
  #db_url: !secret recorder_db_url
