################################################
## Packages / Recorder
################################################

################################################
## Customize
################################################
homeassistant:
  customize:

################################################
## Recorder
################################################
recorder:
  purge_keep_days: 7
  purge_interval: 1
  #db_url: !secret recorder_db_url