################################################
## Packages / Lights
################################################
homeassistant:

################################################
## Scene
################################################
scene:

# ALL
  - name: all_off
    entities:
      light.woonkamer: off
      light.keuken: off
      group.buiten: off

# WOONKAMER
  - name: woonkamer_general
    entities:
      light.woonkamer:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 35
  - name: woonkamer_bright
    entities:
      light.woonkamer:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 50
  - name: woonkamer_super_bright
    entities:
      light.woonkamer:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 90

# KEUKEN
  - name: keuken_general
    entities:
      light.keuken:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 35
      light.keuken_hanglamp:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 25
  - name: keuken_bright
    entities:
      light.keuken:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 50
  - name: keuken_super_bright
    entities:
      light.keuken:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 90

# HAL EN OVERLOPEN
  - name: hal_en_overlopen_general
    entities:
      light.hal_en_overlopen:
        state: true
        transition: 1
        xy_color: [0.52, 0.41]
        brightness_pct: 35
  - name: hal_en_overlopen_night
    entities:
      light.hal_en_overlopen:
        state: true
        transition: 5
        xy_color: [0.52, 0.41]
        brightness_pct: 10
  - name: hal_en_overlopen_bright
    entities:
      light.hal_en_overlopen:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 50
  - name: hal_en_overlopen_super_bright
    entities:
      light.hal_en_overlopen:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 90

# BUITEN
  - name: buiten_general
    entities:
      group.buiten:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 40
  - name: buiten_bright
    entities:
      group.buiten:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 60
  - name: buiten_super_bright
    entities:
      group.buiten:
        state: true
        transition: 3
        xy_color: [0.52, 0.41]
        brightness_pct: 90