################################################
## Packages / Lights
################################################
homeassistant:
  customize:
    scene.slaapkamer_general:
      friendly_name: Slaapkamer On
      icon: mdi:flash
    scene.slaapkamer_wakeup:
      friendly_name: Slaapkamer WakeUp
      icon: mdi:flash
    scene.slaapkamer_bright:
      friendly_name: Slaapkamer Bright
      icon: mdi:flash
    scene.slaapkamer_night:
      friendly_name: Slaapkamer Night
      icon: mdi:flash
    scene.slaapkamer_off:
      friendly_name: Slaapkamer Off
      icon: mdi:flash

################################################
## Scene
################################################
scene:
# ALL
  - name: all_off
    entities:
      light.woonkamer: off
      light.keuken: off
      light.buiten: off

# SLAAPKAMER
  - name: slaapkamer_general
    entities:
      light.slaapkamer:
        state: true
        color_temp: 451
        brightness_pct: 30
  - name: slaapkamer_wakeup
    entities:
      light.slaapkamer:
        state: true
        transition: 300
        color_temp: 451
        brightness_pct: 30
  - name: slaapkamer_bright
    entities:
      light.slaapkamer:
        state: true
        color_temp: 451
        brightness_pct: 50
  - name: slaapkamer_night
    entities:
      light.slaapkamer:
        state: true
        transition: 5
        color_temp: 451
        brightness_pct: 0
  - name: slaapkamer_off
    entities:
      light.slaapkamer: off

# WOONKAMER
  - name: woonkamer_general
    entities:
      light.woonkamer:
        state: true
        transition: 3
        color_temp: 451
        brightness_pct: 50
  - name: woonkamer_bright
    entities:
      light.woonkamer:
        state: true
        transition: 3
        color_temp: 451
        brightness_pct: 50
  - name: woonkamer_super_bright
    entities:
      light.woonkamer:
        state: true
        transition: 3
        color_temp: 451
        brightness_pct: 90
  - name: woonkamer_off
    entities:
      light.woonkamer: off

# KEUKEN
  - name: keuken_general
    entities:
      light.keuken:
        state: true
        transition: 3
        color_temp: 451
        brightness_pct: 50
  - name: keuken_bright
    entities:
      light.keuken:
        state: true
        transition: 3
        color_temp: 451
        brightness_pct: 50
  - name: keuken_super_bright
    entities:
      light.keuken:
        state: true
        transition: 3
        color_temp: 451
        brightness_pct: 90
  - name: keuken_off
    entities:
      light.keuken: off

# HAL EN OVERLOPEN
  - name: hal_en_overlopen_general
    entities:
      light.hal_en_overlopen:
        state: true
        color_temp: 451
        brightness_pct: 40
  - name: hal_en_overlopen_evening
    entities:
      light.hal_en_overlopen:
        state: true
        color_temp: 451
        brightness_pct: 5
  - name: hal_en_overlopen_night
    entities:
      light.hal_en_overlopen:
        state: true
        color_temp: 451
        brightness_pct: 0
  - name: hal_en_overlopen_bright
    entities:
      light.hal_en_overlopen:
        state: true
        color_temp: 451
        brightness_pct: 50
  - name: hal_en_overlopen_super_bright
    entities:
      light.hal_en_overlopen:
        state: true
        color_temp: 451
        brightness_pct: 90

# BUITEN
  - name: buiten_general
    entities:
      light.buiten:
        state: true
        color_temp: 451
        transition: 3
        brightness_pct: 50
  - name: buiten_evening
    entities:
      light.buiten:
        state: true
        color_temp: 451
        brightness_pct: 50
  - name: buiten_night
    entities:
      light.buiten:
        state: true
        color_temp: 451
        brightness_pct: 100
  - name: buiten_bright
    entities:
      light.buiten:
        state: true
        color_temp: 451
        transition: 3
        brightness_pct: 50
  - name: buiten_super_bright
    entities:
      light.buiten:
        state: true
        color_temp: 451
        transition: 3
        brightness_pct: 90
  - name: buiten_off
    entities:
      light.buiten: off

