################################################
## Packages / Speedtest
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    sensor.pihole_status:
       friendly_name: Pi-Hole Status

################################################
## Sensor
################################################
sensor:
  - platform: speedtest
    server_id: 13218
    minute:
      - 0
    monitored_conditions:
      - ping
      - download
      - upload