################################################
## Packages / Thermostats
################################################
homeassistant:
  customize:
    sensor.living_room_thermostat_temperature:
      friendly_name: Temperatuur Nest
    sensor.living_room_thermostat_target:
      friendly_name: Target Temperatuur Nest
    sensor.living_room_thermostat_operation_mode:
      friendly_name: Status Nest
    sensor.living_room_thermostat_humidity:
      friendly_name: Luchtvochtigheid Nest
      icon: mdi:water-percent
    input_number.woonkamer_nest_thermostat_temperature:
      friendly_name: "Temperatuur Woonkamer Nest"

################################################
## Climate
################################################
climate:
  platform: nest

################################################
## Inputs
################################################
input_number:
  woonkamer_nest_thermostat_temperature:
    min: 15
    max: 25
    step: 0.5

################################################
## Sensor
################################################
sensor:
  - platform: nest
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'humidity'
      - 'mode'
      - 'weather_condition'
      - 'weather_temperature'
      - 'weather_humidity'
      - 'wind_speed'
      - 'wind_direction'
      - 'battery_level'
      - 'co_status'
      - 'smoke_status'

  - platform: template
    sensors:
      woonkamer_nest_thermostat_temperature:
        value_template: "{{ states('input_number.woonkamer_nest_thermostat_temperature') | float }}"
      woonkamer_nest_thermostat_target_vs_current:
        value_template: >-
          {%- if states('sensor.living_room_thermostat_temperature') | float != states('sensor.living_room_thermostat_target') | float -%}
            true
          {%- else -%}
            false
          {%- endif -%}
      woonkamer_nest_thermostat_temperature_changed:
        value_template: >-
          {%- if states('input_number.woonkamer_nest_thermostat_temperature') | float != states('sensor.living_room_thermostat_target') | float -%}
            true
          {%- else -%}
            false
          {%- endif -%}

binary_sensor:
  - platform: template
    sensors:
      temp_diff_nest:
        friendly_name: Temperature difference Nest
        value_template: "{{ (states.climate.living_room.attributes.temperature) | float < (states.climate.living_room.attributes.current_temperature) | float }}"

################################################
## Automation
################################################
automation:
  - alias: "Slider - Woonkamer - Nest thermostat - Set value"
    initial_state: on
    trigger:
    - platform: state
      entity_id: sensor.woonkamer_nest_thermostat_temperature_changed
      to: 'true'
      for:
        seconds: 60
    - platform: homeassistant
      event: start
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.woonkamer_nest_thermostat_temperature
        value: "{{ states('sensor.living_room_thermostat_target') | float }}"

  - alias: "Switch - Woonkamer - Nest thermostat - On"
    trigger:
    - platform: state
      entity_id: input_number.woonkamer_nest_thermostat_temperature
    action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.living_room
        preset_mode: 'none'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.living_room
        temperature: "{{ states('input_number.woonkamer_nest_thermostat_temperature') | float }}"
        hvac_mode: heat

  - alias: "Turn off thermostat when leaving"
    trigger:
      - platform: template
        value_template: "{{ states('group.hometracking') != 'home' }}"
    condition:
      - condition: and
        conditions:
          - condition: time
            before: '00:00:00'
            after: '05:00:00'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: 20
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: heat

  # - alias: "Stop Thermostat if current temperature higher than wanted temperature"
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.temp_diff_nest
  #       to: 'on'
  #   condition:
  #     - condition: and
  #       conditions:
  #         - condition: template
  #           value_template: '{{ states.climate.living_room.attributes.preset_mode != "eco" }}'
  #   action:
  #     - service: climate.set_temperature
  #       data:
  #         entity_id: climate.living_room
  #         temperature: 20
  #     - service: climate.set_preset_mode
  #       data:
  #         entity_id: climate.living_room
  #         preset_mode: heat


  - alias: "Set Thermostat Temperature - 0000"
    trigger:
      platform: time
      at: '00:00:00'
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: 20
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: heat

  - alias: "Set Thermostat Temperature - 1500"
    trigger:
      platform: time
      at: '15:00:00'
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: 'none'
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: 22
          hvac_mode: heat

  - alias: "Set Thermostat Temperature - 0500"
    trigger:
      platform: time
      at: '05:00:00'
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.holiday_mode
          state: 'off'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.living_room
          preset_mode: 'none'
      - service: climate.set_temperature
        data:
          entity_id: climate.living_room
          temperature: 22
          hvac_mode: heat
