################################################
## Packages / Trash
################################################
homeassistant:
  customize:
    sensor.trash_today:
      friendly_name: Vandaag
    sensor.trash_tomorrow:
      friendly_name: Morgen
    sensor.trash_next:
      friendly_name: Next pickup in days

    sensor.trash_gft:
      friendly_name: GFT
      entity_picture: /local/mijnafvalwijzer/gft3.png
    sensor.trash_papier:
      friendly_name: Papier
      entity_picture: /local/mijnafvalwijzer/papier3.png
    sensor.trash_pmd:
      friendly_name: Plastic
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.trash_restafval:
      friendly_name: Restafval
      entity_picture: /local/mijnafvalwijzer/rest3.png

    sensor.trash_gft_formatted:
      entity_picture: /local/mijnafvalwijzer/gft3.png
    sensor.trash_papier_formatted:
      entity_picture: /local/mijnafvalwijzer/papier3.png
    sensor.trash_pmd_formatted:
      entity_picture: /local/mijnafvalwijzer/plastic3.png
    sensor.trash_restafval_formatted:
      entity_picture: /local/mijnafvalwijzer/rest3.png
    

################################################
## Inputs
################################################
input_boolean:
  trash_moved:
    name: Trash has been moved
    initial: 'off'
    icon: mdi:delete-empty
  trash_reminder:
    name: Trash reminder enabled
    initial: 'on'

################################################
## Sensor
################################################
sensor:
  - platform: afvalwijzer
    postcode: !secret afvalwijzer_postcode
    huisnummer: !secret afvalwijzer_huisnummer
    #postcode: 4707PB
    #huisnummer: 110
    #weergave: 'Current'

  - platform: template
    sensors:
      trash_gft_formatted:
        entity_id: sensor.trash_gft
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_gft.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_papier_formatted:
        entity_id: sensor.trash_papier
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_papier.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_pmd_formatted:
        entity_id: sensor.trash_pmd
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_pmd.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'
      trash_restafval_formatted:
        entity_id: sensor.trash_restafval
        value_template: '{{ as_timestamp(strptime(states.sensor.trash_restafval.state, "%d-%m-%Y")) | timestamp_custom("%a %d %b") }}'

#  - platform: file
#    file_path: /local/trash.json
#    name: Trash Today
#    value_template: >
#      {% set now = as_timestamp(now()) %}
#      {% set today = now | timestamp_custom("%d/%m/%Y") %}
#      {% set containerType = value_json.days[ today ] %}
#      {% if containerType | trim != "" %}
#        {% set trash = value_json.legend[ containerType ] %}
#        {{ trash }}
#      {% else %}
#        Geen
#      {% endif %}

################################################
## Automation
################################################
automation:
  - alias: Reset trash notification
    trigger:
      platform: state
      entity_id: input_boolean.trash_moved
      to: 'on'
      for:
        hours: 12
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.trash_moved
      - service: input_boolean.turn_on
        entity_id: input_boolean.trash_reminder

  - alias: Mark trash as moved from notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_TRASH_MOVED
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.trash_moved

  - alias: Trash has not been moved
    trigger:
      platform: time_pattern
      minutes: '/30'
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.trash_moved
          state: 'off'
        - condition: state
          entity_id: input_boolean.trash_reminder
          state: 'on'
        - condition: time
          after: '18:00:00'
          before: '23:00:00'
        - condition: template
          value_template: "{{ states('sensor.trash_tomorrow') != 'Geen' }}"
    action:
      - service: notify.family
        data:
          title: "Afval"
          message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.trash_tomorrow.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
          data:
            push:
              badge: 0
              category: 'afval'
