################################################
## Packages / Weather
################################################
homeassistant:
  customize:
    sensor.dark_sky_minutely_summary:
      friendly_name: "Komende uur"
    sensor.dark_sky_hourly_summary:
      friendly_name: "Vandaag"
    sensor.dark_sky_daily_summary:
      friendly_name: "Komende Week"
    sensor.dark_sky_precip_probability:
      friendly_name: "Regen"
    sensor.dark_sky_temperature:
      friendly_name: "Temp"
    sensor.dark_sky_apparent_temperature:
      friendly_name: "Gevoel"
    sensor.dark_sky_humidity:
      friendly_name: "Luchtvocht"
    sensor.dark_sky_wind_speed:
      friendly_name: "Wind"
    sensor.yr_symbol:
      friendly_name: " "
    sensor.yr_temperature:
      friendly_name: " "
    sensor.yr_wind_speed:
      friendly_name: " "
      icon: mdi:weather-windy
    sensor.yr_humidity:
      friendly_name: " "
      icon: mdi:water-percent
    sensor.yr_fog:
      friendly_name: " "
      icon: mdi:weather-fog

################################################
## Sensor
################################################
sensor:
  - platform: darksky
    api_key: !secret darksky_secret
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
