################################################
## Packages / Weather
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'weather'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false
    sensor.dark_sky_minutely_summary:
      <<: *customize
      friendly_name: "Komende uur"
    sensor.dark_sky_hourly_summary:
      <<: *customize
      friendly_name: "Vandaag"
    sensor.dark_sky_daily_summary:
      <<: *customize
      friendly_name: "Komende Week"
    sensor.dark_sky_precip_probability:
      <<: *customize
      friendly_name: "Regen"
    sensor.dark_sky_temperature:
      <<: *customize
      friendly_name: "Temp"
    sensor.dark_sky_apparent_temperature:
      <<: *customize
      friendly_name: "Gevoel"
    sensor.dark_sky_humidity:
      <<: *customize
      friendly_name: "Luchtvocht"
    sensor.dark_sky_wind_speed:
      <<: *customize
      friendly_name: "Wind"

    sensor.yr_symbol:
      <<: *customize
      friendly_name: " "
    sensor.yr_temperature:
      <<: *customize
      friendly_name: " "
    sensor.yr_wind_speed:
      <<: *customize
      friendly_name: " "
      icon: mdi:weather-windy
    sensor.yr_humidity:
      <<: *customize
      friendly_name: " "
      icon: mdi:water-percent
    sensor.yr_fog:
      <<: *customize
      friendly_name: " "
      icon: mdi:weather-fog

################################################
## Sensor
################################################
sensor:
  - platform: darksky
    api_key: !secret darksky_secret
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    update_interval: 00:15
    monitored_conditions:
      - summary
      - precip_probability
      - wind_speed
      - cloud_cover
      - icon
      - temperature_low
      - temperature_high
      - daily_summary
      - hourly_summary
#      - icon
#      - summary
#      - precip_type
#      - precip_intensity
#      - precip_probability
#      - temperature
#      - temperature_low
#      - temperature_high
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_bearing
#      - cloud_cover
#      - humidity
#      - pressure
#      - visibility
#      - ozone
#      - minutely_summary
#      - hourly_summary
#      - daily_summary
#      - precip_intensity_max
#      - uv_index
  - platform: yr
    forecast: 48
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - humidity
      - fog

  - platform: season
  - platform: template
    sensors:
      forecast_0:
        friendly_name: "Today"
        value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}
      forecast_1:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {{ date | timestamp_custom("Tomorrow (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.png'}}
      forecast_2:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.png'}}
      forecast_3:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.png'}}
      forecast_4:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.png'}}
      forecast_5:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.png'}}
      forecast_6:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
            {{states.sensor.dark_sky_daytime_high_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.png'}}
      forecast_7:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (7 * 86400 ) -%}
          {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
        value_template: >
            {{states.sensor.dark_sky_daytime_high_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.png'}}

################################################
## Automation
################################################
#automation:
#- id: update_friendly_names
#  alias: "Update Dark Sky friendly names"
#  initial_state: 'on'
#  trigger:
#    - platform: state
#      entity_id:
#        - sensor.forecast_1
#        - sensor.forecast_2
#        - sensor.forecast_3
#        - sensor.forecast_4
#        - sensor.forecast_5
#        - sensor.forecast_6
#        - sensor.forecast_7
#  action:
#    - service: python_script.dark_sky_friendly_names
#      data_template:
#        entityid: '{{trigger.entity_id}}'
